<?php
/**
 * Copyright © 2018 TechNWeb, Inc. All rights reserved.
 * See TNW_LICENSE.txt for license details.
 */

use Magento\Catalog\Helper\Product\Compare;
use Magento\Wishlist\Helper\Data;

/**
 * @var \Magento\CatalogWidget\Block\Product\ProductsList $block
 * @var \Magento\Framework\Escaper $escaper
 */
?>
<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())): ?>
    <?php
    $_subscriptionBlock = $block->getChildBlock($block->getNameInLayout() . '.tnw.list');
    $type = 'widget-product-grid';

    $mode = 'grid';

    $image = 'new_products_content_widget_grid';
    $items = $block->getProductCollection()->getItems();

    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    $description = false;
    ?>
    <div class="block widget block-products-list <?= /* @noEscape */ $mode ?>">
        <?php if ($block->getTitle()): ?>
            <div class="block-title">
                <strong><?= $block->escapeHtml(__($block->getTitle())) ?></strong>
            </div>
        <?php endif ?>
        <div class="block-content">
            <?= /* @noEscape */ '<!-- ' . $image . '-->' ?>
            <div class="products-<?= /* @noEscape */ $mode ?> <?= /* @noEscape */ $mode ?>">
                <ol class="product-items <?= /* @noEscape */ $type ?>">
                    <?php $iterator = 1; ?>
                    <?php foreach ($items as $_item): ?>
                        <?= /* @noEscape */ ($iterator++ == 1)
                            ? '<li class="product-item">'
                            : '</li><li class="product-item">' ?>
                        <div class="product-item-info">
                            <a href="<?= $escaper->escapeUrl($block->getProductUrl($_item)) ?>"
                               class="product-item-photo">
                                <?= $block->getImage($_item, $image)->toHtml() ?>
                            </a>
                            <div class="product-item-details">
                                <strong class="product-item-name">
                                    <a title="<?= $block->escapeHtml($_item->getName()) ?>"
                                       href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                                       class="product-item-link">
                                        <?= $block->escapeHtml($_item->getName()) ?>
                                    </a>
                                </strong>
                                <?php if ($templateType): ?>
                                    <?= $block->getReviewsSummaryHtml($_item, $templateType) ?>
                                <?php endif; ?>
                                <strong class="product name product-item-name">
                                    <?= $escaper->escapeHtml($_subscriptionBlock->getTopMessage($_item)) ?>
                                </strong>
                                <?php if ($_subscriptionBlock->isAllowedProductType($_item)
                                    && $_subscriptionBlock->isSubscriptionPrice($_item)): ?>
                                    <div class="price-box price-final_price">
                                        <?= /* @noEscape */ $_subscriptionBlock->getPriceLabel($_item) ?>
                                        <span class="price-wrapper" data-role="priceBox">
                                            <span class="price">
                                                <?= /* @noEscape */ $_subscriptionBlock
                                                    ->getTrialPriceForCategory($_item) ?>
                                            </span>
                                        </span>
                                    </div>
                                <?php else: ?>
                                    <?= /* @noEscape */ $block->getProductPriceHtml($_item) ?>
                                <?php endif; ?>

                                <?= $block->getProductDetailsHtml($_item) ?>

                                <?php if ($showWishlist || $showCompare || $showCart): ?>
                                    <div class="product-item-inner">
                                        <div class="product-item-actions">
                                        <?php if ($showCart): ?>
                                            <?php
                                            $_subscriptionBlock->prepareParamsToButtonsBlock(
                                                $_item,
                                                null,
                                                'grid',
                                                '',
                                                $block->getAddToCartPostParams($_item)
                                            );
                                            echo $_subscriptionBlock->getButtonsHtml();
                                            ?>
                                        <?php endif; ?>
                                        <?php if ($showWishlist || $showCompare): ?>
                                            <div class="actions-secondary" data-role="add-to-links">
                                                <?php if ($this->helper(Data::class)->isAllow()
                                                    && $showWishlist): ?>
                                                    <a href="#"
                                                       data-post='<?= /* @noEscape */ $block->getAddToWishlistParams($_item) ?>'
                                                       class="action towishlist"
                                                       data-action="add-to-wishlist"
                                                       title="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>">
                                                        <span><?= $block->escapeHtml(__('Add to Wish List')) ?></span>
                                                    </a>
                                                <?php endif; ?>
                                                <?php if ($block->getAddToCompareUrl() && $showCompare): ?>
                                                    <?php $compareHelper = $this->helper(Compare::class);?>
                                                    <a href="#" class="action tocompare"
                                                       data-post='<?= /* @noEscape */ $compareHelper->getPostDataParams($_item) ?>'
                                                       title="<?= $block->escapeHtmlAttr(__('Add to Compare')) ?>">
                                                        <span><?= $block->escapeHtml(__('Add to Compare')) ?></span>
                                                    </a>
                                                <?php endif; ?>
                                            </div>
                                        <?php endif; ?>
                                        </div>
                                    </div>
                                <?php endif; ?>
                            </div>
                        </div>
                        <?= ($iterator == count($items) + 1) ? '</li>' : '' ?>
                    <?php endforeach ?>
                </ol>
            </div>
            <?= $block->getPagerHtml() ?>
        </div>
    </div>
<?php endif;?>
