<?php  //[STAMP] 40372817770a4610192d7bc58d64e7ec
namespace TNW_Subscriptions\_generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile

trait FunctionalTesterActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();

    
    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Log in as an admin user
     * @see \TNW_Subscriptions\Helper\Acceptance::logInAsAdminUser()
     */
    public function logInAsAdminUser() {
        return $this->getScenario()->runStep(new \Codeception\Step\Action('logInAsAdminUser', func_get_args()));
    }
}
