<?php  //[STAMP] 47ce8bb0728c1cd476d7ab7485c3d210
namespace TNW_Subscriptions\_generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile

trait FunctionalTesterActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();

    
}
