<?php
/**
 * Copyright © 2018 TechNWeb, Inc. All rights reserved.
 * See TNW_LICENSE.txt for license details.
 */

/* @var $block \TNW\Subscriptions\Block\Product\View\Subscribe */
/* @var $customerProductsHistoryListViewModel \TNW\Subscriptions\Block\Product\CustomerProductsHistoryList */
$customerProductsHistoryListViewModel = $block->getData('customerProductsHistoryList');
?>
<?php $block->getProduct()->setPriceCalculation()?>
<div class="subscribe-container">
    <div id="subscribe-container" data-bind="scope: 'recurringAddToCart'">
        <!-- ko template: getTemplate() --><!-- /ko -->
    </div>
    <script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "recurringAddToCart": {
                        "component": "TNW_Subscriptions/js/product/subscribe-component",
                        "config": {
                            "defaultFrequency" : "<?= $block->getDefaultFrequency() ?>",
                            "buttonLabel" : "<?= $block->escapeHtml(__('Update cart')) ?>",
                            "dateFormat": "<?= $block->getDateFormat() ?>",
                            "minStartOn" : "<?= $block->getMinStartOn() ?>",
                            "defaultPeriod" : "<?= $block->getDefaultPeriod() ?>",
                            "defaultUntilCancelled" : "<?= $block->getDefaultUntilCancelled() ?>",
                            "defaultSubscribeQty" : "<?= $block->getDefaultSubscribeQty() ?>",
                            "defaultStartOn" : "<?= $block->getDefaultStartOn() ?>",
                            "products" : <?= $block->getProductDataArray() ?>,
                            "defaultIsTrial" : <?= $block->getIsTrial() ?>,
                            "isTrialAvailableForUser" : "<?= /* @noEscape */ $customerProductsHistoryListViewModel->isProductTrialAvailableForCurrentCustomer($block->getProduct()->getId()) ?>"
                        }
                    }
                }
            }
        }
    }
    </script>
</div>
