<?php
/**
 * Copyright © 2017 TechNWeb, Inc. All rights reserved.
 * See TNW_LICENSE.txt for license details.
 */
?>
<?php /** @var TNW\Subscriptions\Block\Adminhtml\Sales\Order\Creditmemo\InitialFee $block */
$_source = $block->getSource() ?>
<?php if ($_source): ?>
    <tr class="initial-fee-container">
        <td class="label">
            <?php /* @escapeNotVerified */echo __('Initial Fee') ?>
            <div id="subscription_initial_fee_adv"></div>
        </td>
        <td>
            <div class="total-value">
                <?php /* @escapeNotVerified */echo $block->getInitialFeeTotalValue() ?>
            </div>
            <input type="text"
                   name="creditmemo[subscription_initial_fee]"
                   value="<?php /* @escapeNotVerified */ echo $block->getBaseInitialFee() * 1 ?>"
                   class="input-text admin__control-text not-negative-amount"
                   id="subscription_initial_fee"/>
        </td>
    </tr>
<?php endif; ?>
