<?php
/**
 * Copyright © 2018 TechNWeb, Inc. All rights reserved.
 * See TNW_LICENSE.txt for license details.
 */

/**
 * @var $block \TNW\Subscriptions\Block\Subscription\Product\Edit
 * @var $escaper \Magento\Framework\Escaper
 */
?>
<div class="subscribe-container">
    <input type="hidden" name="sub_product_id" value="<?= /* @noEscape */ $block->getSubscriptionProductId()?>" />
    <div class="fieldset">
        <div class="field required">
            <label class="label"><span><?= $escaper->escapeHtml(__('Billing Frequency')) ?>:</span></label>
            <div class="control">
                <div class="options-list nested">
                    <?php $currenctFrequency = $block->getCurrentFrequencyData()?>
                    <div class="field choice required">
                        <label class="label billing_frequency">
                            <span><?= $escaper->escapeHtml($currenctFrequency['label']) ?></span>
                        </label>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="fieldset">
        <div class="field term">
            <label class="label"><span><?= $escaper->escapeHtml(__('Term')) ?>:</span></label>
            <div class="control">
                <label class="label term">
                    <span><?= $escaper->escapeHtml($block->getSubscriptionPeriodLabel()) ?></span>
                </label>
            </div>
        </div>
    </div>
    <div class="fieldset">
        <div class="field">
            <label class="label" for="start_at"><span><?= $escaper->escapeHtml(__('Start On')) ?>:</span></label>
            <div class="control">
                <label class="label starton">
                    <span><?= $escaper->escapeHtml($block->getStartOn()) ?></span>
                </label>
            </div>
        </div>
    </div>
    <div class="fieldset <?php if (!$block->getAllowDisplaySubscribeQty()): ?>
        hidden
    <?php endif; ?>">
        <div class="field required">
            <label class="label" for="subscribe_qty"><span><?= $escaper->escapeHtml(__('Qty')) ?>:</span></label>
            <div class="control">
                <input type="number"
                       name="subscribe_qty"
                       id="subscribe_qty"
                       maxlength="12"
                       value="<?= $block->getSubProductQty() * 1 ?>"
                       title="<?= $escaper->escapeHtml(__('Qty')) ?>"
                       class="input-text qty"
                       data-validate='<?= $escaper->escapeHtml(\json_encode($block->getQtyValidators())) ?>'
                    <?php if (!$block->getAllowEditSubscribeQty()): ?>
                       readonly="readonly"
                    <?php endif ?>
                />
            </div>
        </div>
    </div>
    <button type="submit"
            id="product-subscribe-button"
            title="<?= $escaper->escapeHtml(__('Update')) ?>"
            class="action primary subscribe">
        <span data-role="button-text"><?= $escaper->escapeHtml(__('Update')) ?></span>
    </button>
</div>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "tnwSubscribeContainer": {
                "setQtyFromFrequency": <?= $block->getAllowEditSubscribeQty() ? 'false' : 'true' ?>,
                "canShowSubscribePriceBlock" : true,
                "savingsCalculationType" : "<?= $escaper->escapeHtml($block->getSavingCalculationType()) ?>",
                "product" : <?= /* @noEscape  */ $block->getProductDataArray() ?>
            }
        }
    }
</script>
