<?php
/**
 * Copyright © 2018 TechNWeb, Inc. All rights reserved.
 * See TNW_LICENSE.txt for license details.
 */

/** @var \TNW\Subscriptions\Block\Adminhtml\SubscriptionProfile\Review\Address $this */
?>

<div class="admin__page-section-item subscription-profile-<?= $this->getAddressType() ?>-address">
    <div class="admin__page-section-item-content"><?= /* @escapeNotVerified */ $this->getAddress(); ?></div>
</div>
</br>
