Listen 8080

<VirtualHost *:8080>
  DocumentRoot /var/www/html/magento
  ServerName magento-qa.box
  DirectoryIndex index.php
  LogLevel notice

  <FilesMatch \.php$>
    SetHandler application/x-httpd-php
  </FilesMatch>

  <Directory /var/www/html/magento>
    Options Indexes FollowSymLinks
    AllowOverride All
    Require all granted
  </Directory>

</VirtualHost>
