<?php
/**
 *  Copyright © 2018 TechNWeb, Inc. All rights reserved.
 *  See TNW_LICENSE.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<?php
/** @var \TNW\Subscriptions\Pricing\Render\SubscriptionPriceBox $block */

$productId = $block->getSaleableItem()->getId();

/** ex: \Magento\Catalog\Pricing\Price\RegularPrice */
/** @var \Magento\Framework\Pricing\Price\PriceInterface $priceModel */
$priceModel = $block->getPriceType('regular_price');

/** ex: \Magento\Catalog\Pricing\Price\FinalPrice */
/** @var \Magento\Framework\Pricing\Price\PriceInterface $finalPriceModel */
$finalPriceModel = $block->getPriceType('final_price');
$idSuffix = $block->getIdSuffix() ? $block->getIdSuffix() : '';
$schema = ($block->getZone() == 'item_view') ? true : false;
?>
<?php
    $data = $block->renderSubscriptionAmounts(
        $finalPriceModel->getAmount(),
        $block->getProduct(),
        [
            'price_id'          => $block->getPriceId('product-price-' . $idSuffix),
            'price_type'        => 'finalPrice',
            'include_container' => true,
            'schema' => $schema,
        ]
    );
    $data = $block->getEncodedData($data);
?>
<?php if ($block->getConfigOnly()): ?>
<?= $data ?>
<?php else: ?>
<script type="text/x-magento-init">
{
    ".product-info-price": {
        "tnwSubscribePrice": {
            "subscriptionPricesData" : <?= /* @noEscape */ $data ?>,
            "subBillingFrequencyId" : <?= /* @noEscape */ $block->getBillingFrequencyId() ?>
        }
    }
}
</script>
<?php endif; ?>
