<?php
/**
 * Copyright © 2018 TechNWeb, Inc. All rights reserved.
 * See TNW_LICENSE.txt for license details.
 */

/**
 * @var \TNW\Subscriptions\Pricing\Render\SubscriptionAmount $block
 */

?>
<?php if ($topMessage = $block->getMessage('top')): ?>
    <div class="subscription-price-top-messages">
        <?= /* @noEscape */ $block->getMessage('top') ?>
    </div>
<?php endif; ?>
<span class="price-container <?= /* @noEscape */ $block->getAdjustmentCssClasses() ?>"
        <?= $block->getSchema() ? ' itemprop="offers" itemscope itemtype="http://schema.org/Offer"' : '' ?>>
    <span <?php if ($block->getPriceId()): ?> id="<?= /* @noEscape */ $block->getPriceId() ?>"<?php endif;?>
        <?= /* @noEscape */ ($block->getPriceDisplayLabel())
            ? 'data-label="' . $block->getPriceDisplayLabel() . $block->getPriceDisplayInclExclTaxes() . '"'
            : '' ?>
        data-price-amount="<?= /* @noEscape */ $block->getPrice(); ?>"
        data-price-type="<?= /* @noEscape */ $block->getPriceType(); ?>"
        class="price-wrapper <?= /* @noEscape */ $block->getPriceWrapperCss(); ?>"
        <?= $block->getSchema() ? ' itemprop="price"' : '' ?>>
        <?= /* @noEscape */ $block->getDisplayPrice() ?>
    </span>
    <?php if ($block->getSchema()): ?>
        <meta itemprop="priceCurrency" content="<?= /* @noEscape */ $block->getDisplayCurrencyCode()?>" />
    <?php endif; ?>
</span>
<?php if ($bottomMessage = $block->getMessage('bottom')): ?>
    <div class="subscription-price-bottom-messages">
        <?= /* @noEscape */ $bottomMessage ?>
    </div>
<?php endif; ?>
<?php if ($block->getOldPrice()): ?>
    <?= /* @noEscape */ $block->getDisplayOldPrice() ?>
<?php endif; ?>
