<?php
/**
 * Copyright © 2018 TechNWeb, Inc. All rights reserved.
 * See TNW_LICENSE.txt for license details.
 */

/** @var \TNW\Subscriptions\Pricing\Render\SubscriptionAmount $block */
?>
<?php if ($topMessage = $block->getMessage('top')): ?>
    <div class="subscription-price-top-messages">
        <?= $block->getMessage('top') ?>
    </div>
<?php endif; ?>
<span class="price-container <?= /* @escapeNotVerified */ $block->getAdjustmentCssClasses() ?>"
        <?= $block->getSchema() ? ' itemprop="offers" itemscope itemtype="http://schema.org/Offer"' : '' ?>>
    <span <?php if ($block->getPriceId()): ?> id="<?= /* @escapeNotVerified */ $block->getPriceId() ?>"<?php endif;?>
        <?=($block->getPriceDisplayLabel()) ? 'data-label="' . $block->getPriceDisplayLabel() . $block->getPriceDisplayInclExclTaxes() . '"' : '' ?>
        data-price-amount="<?= /* @escapeNotVerified */ $block->getPrice(); ?>"
        data-price-type="<?= /* @escapeNotVerified */ $block->getPriceType(); ?>"
        class="price-wrapper <?= /* @escapeNotVerified */ $block->getPriceWrapperCss(); ?>"
        <?= $block->getSchema() ? ' itemprop="price"' : '' ?>>
        <?= $block->getDisplayPrice() ?>
    </span>
    <?php if ($block->getSchema()): ?>
        <meta itemprop="priceCurrency" content="<?= /* @escapeNotVerified */ $block->getDisplayCurrencyCode()?>" />
    <?php endif; ?>
</span>
<?php if ($bottomMessage = $block->getMessage('bottom')): ?>
    <div class="subscription-price-bottom-messages">
        <?= $bottomMessage ?>
    </div>
<?php endif; ?>