<?php /* @var \TNW\Subscriptions\Block\Subscription\Summary\Shipping\Details $block */ ?>
<div class="block">
    <div class="block-title">
        <strong><?php echo __("Shipping Details") ?></strong>
        <?php if ($block->isShowEditLink()) : ?>
            <a href="<?php echo $block->getUrl('tnw_subscriptions/subscription/shipment', ['entity_id' => $block->getSubscriptionProfile()->getId()]) ?>" class="profile__edit_button"></a>
        <?php endif;?>
    </div>
    <div class="block-content">
        <table class="table-secondary data-table">
            <tbody>
            <tr class="col-0">
                <td class="label"><?php echo __("Shipping Method") ?></td>
                <td class="right"><?php echo $block->getShippingDescription() ?></td>
            </tr>
            </tbody>
        </table>
    </div>
</div>