<?php
/**
 * Copyright © 2018 TechNWeb, Inc. All rights reserved.
 * See TNW_LICENSE.txt for license details.
 */
?>
<?php
/**
 * Product list template
 *
 * @var $block \TNW\Subscriptions\Block\Product\ListProduct
 * @var $imageBlockBuilder \Magento\Catalog\Block\Product\ImageBlockBuilder
 * @var $escaper \Magento\Framework\Escaper
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_subscriptionBlock = $block->getChildBlock('helper.category.products.list');
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty">
        <div><?= $escaper->escapeHtml(__('We can\'t find products matching the selection.')) ?></div>
    </div>
<?php else: ?>
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $imageDisplayArea = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $imageDisplayArea = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?= /* @noEscape */ $viewMode; ?> products-<?= /* @noEscape */ $viewMode; ?>">
        <?php $iterator = 1; ?>
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
                <?= /* @noEscape */($iterator++ == 1) ? '<li class="item product product-item">'
                    : '</li><li class="item product product-item">' ?>
                <div class="product-item-info" data-container="product-grid">
                    <?php
                    $productImage = $block->getImage($_product, $imageDisplayArea);
                    $position = '';
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
                    <?php // Product Image ?>
                    <a href="<?= /* @noEscape */ $_product->getProductUrl() ?>"
                       class="product photo product-item-photo" tabindex="-1">
                        <?= $productImage->toHtml(); ?>
                    </a>
                    <div class="product details product-item-details">
                        <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                        <strong class="product name product-item-name">
                            <a class="product-item-link"
                               href="<?= /* @noEscape */ $_product->getProductUrl() ?>">
                                <?= $escaper->escapeHtml(
                                    $_helper->productAttribute($_product, $_product->getName(), 'name')
                                ); ?>
                            </a>
                        </strong>
                        <?= $block->getReviewsSummaryHtml($_product, $templateType); ?>
                        <strong class="product name product-item-name">
                            <?= $escaper->escapeHtml($_subscriptionBlock->getTopMessage($_product)) ?>
                        </strong>
                            <?php if ($_subscriptionBlock->isAllowedProductType($_product)
                                && $_subscriptionBlock->isSubscriptionPrice($_product)): ?>
                            <div class="price-box price-final_price">
                                <span class="price-wrapper" data-role="priceBox">
                                    <span class="price">
                                        <?= /* @noEscape */ $_subscriptionBlock->getTrialPriceForCategory($_product) ?>
                                    </span>
                                </span>
                            </div>
                        <?php else: ?>
                            <?= /* @noEscape */ $block->getProductPrice($_product) ?>
                        <?php endif; ?>
                        <?= $block->getProductDetailsHtml($_product); ?>

                        <div class="product-item-inner">
                            <div class="product actions product-item-actions"<?= /* @noEscape */
                                    strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
                                <?php
                                $_subscriptionBlock->prepareParamsToButtonsBlock(
                                    $_product,
                                    $pos,
                                    $viewMode,
                                    $position,
                                    $block->getAddToCartPostParams($_product)
                                );
                                echo $_subscriptionBlock->getButtonsHtml();
                                ?>
                                <div data-role="add-to-links" class="actions-secondary"<?= /* @noEscape */
                                        strpos($pos, $viewMode . '-secondary') ? $position : ''; ?>>
                                    <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                        <?= $addToBlock->setProduct($_product)->getChildHtml(); ?>
                                    <?php endif; ?>
                                </div>
                            </div>
                            <?php if ($showDescription):?>
                                <div class="product description product-item-description">
                                    <?= $escaper->escapeHtml($_helper->productAttribute(
                                        $_product,
                                        $_product->getShortDescription(),
                                        'short_description'
                                    )) ?>
                                    <a href="<?= /* @noEscape */ $_product->getProductUrl() ?>"
                                       title="<?= $escaper->escapeHtml($_productNameStripped) ?>"
                                       class="action more"><?= $escaper->escapeHtml(__('Learn More')) ?></a>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
                <?=($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
            <?php endforeach; ?>
        </ol>
    </div>
    <?= $block->getToolbarHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()): ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-subscriptions-form]": {
                "catalogAddToCart": {
                    "addToCartButtonTextDefault" : "<?= $escaper->escapeHtml(__('Auto-Ship')) ?>"
                    }
            },
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
