<?php
/**
 * Copyright © 2018 TechNWeb, Inc. All rights reserved.
 * See TNW_LICENSE.txt for license details.
 */

/* @var $block \TNW\Subscriptions\Block\Subscription\Info\Billing */
?>
<div class="subscription-data-wrapper"
     data-mage-init='{"tnwSubscribeBilling":{
        "saveAddressUrl": "<?= $block->escapeUrl($block->getSaveAddressUrl()) ?>",
        "showEdit": "<?= /* @noEscape */ $block->isShowEdit() ?>",
        "showEditDetails": "<?= /* @noEscape */ $block->isShowEditDetails() ?>",
        "customerAddressesData": "<?= $block->escapeQuote($block->getCustomerAddressesData())?>",
        "emptyCountryLabel": "<?= /* @noEscape */ __('Country') ?>"
    }}'>
    <?= $block->getTabMessagesHtml(); ?>
    <div class="grid-row">
        <div class="billing-info-content grid-col2-lg">
            <div id="billing-info-view"><?= $block->getBillingInfoViewHtml() ?></div>
            <div id="billing-info-edit" style="display: none"><?= $block->getBillingInfoEditHtml() ?></div>
        </div>
        <div class="payment-details-content grid-col2-lg">
            <div id="payment-details-view">
                <?= $block->getPaymentDetailsViewHtml() ?>
            </div>
            <div id="payment-details-edit">
                <?= $block->getPaymentDetailsEditHtml() ?>
            </div>
        </div>
    </div>
    <div class="grid-row">
        <div class="coupon-info-content grid-col2-lg">
            <div id="coupon-info-view">
                <?= $block->getCouponDetailsViewHtml() ?>
            </div>
        </div>
    </div>
</div>
