<?php
/**
 * Copyright © 2018 TechNWeb, Inc. All rights reserved.
 * See TNW_LICENSE.txt for license details.
 */

/** @var $block TNW\Subscriptions\Block\Subscription\EditForm */
?>
<form class="<?= $block->getFormClass()?>"
      id="<?= $block->getFormId()?>"
      enctype="multipart/form-data"
      data-hasrequired="<?= /* @escapeNotVerified */ __('* Required Fields') ?>"
      method="post">
    <?= $block->getFormContentHtml() ?>
    <div class="actions-toolbar">
        <div class="grid-row">
            <div class="primary grid-col2-xs">
                <button id="<?= $block->getSaveButtonId()?>"
                        class="action save primary"
                        title="<?= /* @escapeNotVerified */ __('Save') ?>">
                    <span><?= /* @escapeNotVerified */ __('Save') ?></span>
                </button>
            </div>
            <div class="secondary grid-col2-xs">
                <button id="<?= $block->getCancelButtonId()?>"
                        class="action cancel"
                        data-action="cancel"
                        title="<?= /* @escapeNotVerified */ __('Cancel') ?>">
                    <span><?= /* @escapeNotVerified */ __('Cancel') ?></span>
                </button>
            </div>
        </div>
    </div>
</form>
