<?php
/**
 * Copyright © 2018 TechNWeb, Inc. All rights reserved.
 * See TNW_LICENSE.txt for license details.
 */

/* @var $block \TNW\Subscriptions\Block\Subscription\Info\OrderHistory */
?>
<?php $_orderHistory = $block->getOrderHistory(); ?>
<?php if ($_orderHistory && count($_orderHistory)): ?>
    <div class="table-wrapper orders-history">
        <table class="data table table-order-items history" id="my-orders-table">
            <caption class="table-caption"><?= /* @escapeNotVerified */ __('Order History') ?></caption>
            <thead>
            <tr>
                <th scope="col" class="col id"><?= /* @escapeNotVerified */ __('Order #') ?></th>
                <th scope="col" class="col date"><?= /* @escapeNotVerified */ __('Created On') ?></th>
                <th scope="col" class="col tax-fee"><?= /* @escapeNotVerified */ __('Tax Fee') ?></th>
                <th scope="col" class="col shipping-fee"><?= /* @escapeNotVerified */ __('Shipping Fee') ?></th>
                <th scope="col" class="col total"><?= /* @escapeNotVerified */ __('Grand Total') ?></th>
                <th scope="col" class="col status"><?= /* @escapeNotVerified */ __('Status') ?></th>
            </tr>
            </thead>
            <tbody>
            <?php /** @var \Magento\Sales\Model\Order $_order */ foreach ($_orderHistory as $_order): ?>
                <tr>
                    <td data-th="<?= $block->escapeHtml(__('Order #')) ?>" class="col id">
                        <a href="<?= /* @escapeNotVerified */ $block->getViewUrl($_order) ?>" class="action view">
                            <span><?= /* @escapeNotVerified */ $_order->getRealOrderId() ?></span>
                        </a>
                    </td>
                    <td data-th="<?= $block->escapeHtml(__('Created On')) ?>" class="col status"><?= /* @escapeNotVerified */ $block->formatDate($_order->getCreatedAt()) ?></td>
                    <td data-th="<?= $block->escapeHtml(__('Tax Fee')) ?>" class="col status"><?= /* @escapeNotVerified */ $_order->formatPrice($_order->getTaxAmount()); ?></td>
                    <td data-th="<?= $block->escapeHtml(__('Shipping Fee')) ?>" class="col status"><?= /* @escapeNotVerified */ $block->getShippingFeeByOrder($_order); ?></td>
                    <td data-th="<?= $block->escapeHtml(__('Grand Total')) ?>" class="col total"><?= /* @escapeNotVerified */ $_order->formatPrice($_order->getGrandTotal()) ?></td>
                    <td data-th="<?= $block->escapeHtml(__('Status')) ?>" class="col status"><?= /* @escapeNotVerified */ $_order->getStatusLabel() ?></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php if ($block->getPagerHtml()): ?>
        <div class="order-products-toolbar toolbar bottom"><?= $block->getPagerHtml(); ?></div>
    <?php endif ?>
<?php else: ?>
    <div class="message info empty"><span><?= /* @escapeNotVerified */ __('You have placed no orders.'); ?></span></div>
<?php endif ?>
