<?php
/**
 * Copyright © 2018 TechNWeb, Inc. All rights reserved.
 * See TNW_LICENSE.txt for license details.
 */

/* @var $block \TNW\Subscriptions\Block\Subscription\History */
?>
<?php $subscriptionsCollection = $block->getSubscriptionsCollection(); ?>
<?php if ($subscriptionsCollection && count($subscriptionsCollection)): ?>
    <div class="table-wrapper subscriptions-history">
        <table class="data table table-subscriptions-items history" id="my-subscriptions-table">
            <caption class="table-caption"><?= /* @escapeNotVerified */ __('Subscriptions') ?></caption>
            <thead>
            <tr>
                <th scope="col" class="col icon"></th>
                <th scope="col" class="col id"><?= /* @escapeNotVerified */ __('Subscription #') ?></th>
                <th scope="col" class="col date"><?= /* @escapeNotVerified */ __('Next Payment On') ?></th>
                <th scope="col" class="col date"><?= /* @escapeNotVerified */ __('Billing Frequency') ?></th>
                <th scope="col" class="col status"><?= /* @escapeNotVerified */ __('Status') ?></th>
                <th scope="col" class="col next-payment"><?= /* @escapeNotVerified */ __('Next Payment') ?></th>
                <th scope="col" class="col actions"><?= /* @escapeNotVerified */ __('Action') ?></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($subscriptionsCollection as $subscription): ?>
                <tr>
                    <td data-th="" class="sub-icons-container">
                        <?php if ($block->getIconSubClass($subscription)): ?>
                            <div class="sub-icon tooltip-toggle <?= /* @noEscape */ $block->getIconSubClass($subscription) ?>"></div>
                        <?php endif; ?>
                        <div class="sub-message tooltip-content">
                            <?= /* @noEscape */ $block->getStatusMessage($subscription) ?>
                        </div>
                    </td>
                    <td data-th="<?= $block->escapeHtml(__('Subscription #')) ?>" class="col id">
                        <a href="<?= /* @noEscape */ $block->getEditUrl($subscription) ?>">
                            <?= /* @escapeNotVerified */ $subscription->getLabel() ?>
                        </a>
                    </td>
                    <td data-th="<?= $block->escapeHtml(__('Next Payment On')) ?>" class="col date">
                        <?= /* @escapeNotVerified */ $block->getNextPaymentFormatted($subscription); ?>
                    </td>
                    <td data-th="<?= $block->escapeHtml(__('Billing Frequency')) ?>" class="col date">
                        <?= /* @escapeNotVerified */ $block->getBillingFrequency($subscription->getId()); ?>
                    </td>
                    <td data-th="<?= $block->escapeHtml(__('Status')) ?>"
                        class="col status <?= /* @noEscape */ $block->getStatusClass($subscription->getStatus())?>">
                        <?= /* @escapeNotVerified */ $block->getStatusLabel($subscription->getStatus()) ?>
                    </td>
                    <td data-th="<?= $block->escapeHtml(__('Next Payment')) ?>" class="col next-payment">
                        <?= /* @escapeNotVerified */ $block->formatPrice($subscription->getGrandTotal(), $subscription->getCurrencyCode()) ?>
                    </td>
                    <td data-th="<?= $block->escapeHtml(__('Action')) ?>" class="col actions">
                        <?php if ($block->canHoldSubscription($subscription)): ?>
                            <a href="<?= /* @escapeNotVerified */ $block->getHoldUrl($subscription->getId()) ?>" class="action sub-hold">
                                <span><?= /* @escapeNotVerified */ __('Hold') ?></span>
                            </a>
                        <?php endif; ?>
                        <?php if ($block->canReActiveSubscription($subscription)): ?>
                            <a href="<?= /* @escapeNotVerified */ $block->getReActivateUrl($subscription->getId()) ?>" class="action sub-reactivate">
                                <span><?= /* @escapeNotVerified */ __('Re-activate') ?></span>
                            </a>
                        <?php endif; ?>
                        <?php if ($block->canCancelSubscription($subscription)): ?>
                            <a href="<?= /* @escapeNotVerified */ $block->getCancelUrl($subscription->getId()) ?>" class="action sub-cancel">
                                <span><?= /* @escapeNotVerified */ __('Cancel') ?></span>
                            </a>
                        <?php endif; ?>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php if ($block->getPagerHtml()): ?>
        <div class="subscriptions-products-toolbar toolbar bottom"><?= $block->getPagerHtml(); ?></div>
    <?php endif ?>
<?php else: ?>
    <div class="message info empty">
        <span><?= /* @escapeNotVerified */ __('You have placed no subscriptions.'); ?></span>
    </div>
<?php endif ?>
