<?php /* @var \TNW\Subscriptions\Block\Subscription\Summary\EmailOverview $block */ ?>
<?= $block->getProductsHtml() ?>
<?= $block->getCouponDetails() ?>

<table class="order-details">
    <tbody>
    <tr>
        <td>
            <?php if ($block->canShowShippingDetailsBlock()): ?>
                <?= $block->getShippingInfoHtml() ?>
            <?php endif; ?>
        </td>
        <td>
            <?php if ($block->canShowShippingDetailsBlock()): ?>
                <?= $block->getShippingDetailsHtml() ?>
            <?php endif; ?>
        </td>
    </tr>
    <tr>
        <td><?= $block->getBillingInfoHtml() ?></td>
        <td><?= $block->getPaymentDetailsHtml() ?></td>
    </tr>
    </tbody>
</table>
