<?php /* @var \TNW\Subscriptions\Block\Subscription\Summary\Products $block */ ?>

<h3><?= $block->escapeHtml(__('Products')) ?></h3>
<table class="email-items">
    <thead>
        <tr>
            <th class="item-info">
                <?= $block->escapeHtml(__('Item')) ?>
            </th>
            <th class="item-qty">
                <?= $block->escapeHtml(__('Qty')) ?>
            </th>
            <th class="item-subscription">
                <?= $block->escapeHtml(__('Subscription Details')) ?>
            </th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($block->getItems() as $item): ?>
        <tr>
            <td class="item-info">
                <p class="product-name"><?php echo $block->getName($item) ?></p>
                <dl class="item-options custom-attributes">
                    <?php foreach ($block->getItemOptions($item) as $option): ?>
                        <dt><?= $block->escapeHtml($option['label']) ?></dt>
                        <?php $formatedOptionValue = $block->getFormatedOptionValue($option) ?>
                        <dd>
                            <?php if (isset($formatedOptionValue['full_view'])): ?>
                                <?= /* @escapeNotVerified */ $formatedOptionValue['full_view'] ?>
                            <?php else: ?>
                                <?= /* @escapeNotVerified */ $formatedOptionValue['value'] ?>
                            <?php endif; ?>
                        </dd>
                    <?php endforeach; ?>
                    <?php foreach ($block->customAttributes($item) as $attribute): ?>
                        <dt><?php echo $block->escapeHtml($attribute->getDefaultFrontendLabel()) ?></dt>
                        <dd><?php echo $block->escapeHtml($attribute->getFrontend()->getValue($item)) ?></dd>
                    <?php endforeach; ?>
                </dl>
            </td>
            <td class="item-qty">
                <span class="qty"><?php echo __('Qty') ?></span>:
                <span><?php echo (int)$item->getQty() ?></span>
            </td>
            <td class="item-subscription-info">
                <dt><?php echo __('Billing Frequency') ?></dt>
                <dd><?php echo $block->getBillingFrequencyLabel() ?></dd>
                <dt><?php echo __('Term') ?></dt>
                <dd><?php echo $block->getTerm() ?></dd>
                <dt><?php echo __('Start on') ?></dt>
                <dd><?php echo $block->getStartOnFormatted() ?></dd>
                <dt><?php echo __('Price') ?></dt>
                <dd><?php echo $block->formatPrice($item->getPrice()) ?></dd>
                <?php if ($taxAmount = $item->getTaxAmount($block->getSubscriptionProfile())): ?>
                    <dt><?php echo __('Tax') ?></dt>
                    <dd><?php echo $block->formatPrice($taxAmount) ?></dd>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<p class="product-frequency-description">
    <?php echo $block->getFrequencyDescription() ?>
</p>
