<?php
/**
 * Copyright © 2018 TechNWeb, Inc. All rights reserved.
 * See TNW_LICENSE.txt for license details.
 */

// @codingStandardsIgnoreFile
/** @var TNW\Subscriptions\Block\Checkout\Link $block */
?>
<button type="button"
        data-role="proceed-to-checkout"
        title="<?= /* @escapeNotVerified */ __('Proceed to Checkout') ?>"
        data-mage-init='{"Magento_Checkout/js/proceed-to-checkout":{"checkoutUrl":"<?= /* @escapeNotVerified */ $block->getCheckoutUrl() ?>"}}'
        class="action primary checkout<?= ($block->isDisabled()) ? ' disabled' : '' ?>"
        <?php if ($block->isDisabled()):?>disabled="disabled"<?php endif; ?>>
    <span><?= /* @escapeNotVerified */ __('Proceed to Checkout') ?></span>
</button>
