<?php
/**
 * Copyright © 2018 TechNWeb, Inc. All rights reserved.
 * See TNW_LICENSE.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/** @var $block \Magento\Checkout\Block\Onepage\Success */
/** @var $profileSuccessViewModel \TNW\Subscriptions\Block\Checkout\ProfileSuccessViewModel */
$profileSuccessViewModel = $block->getProfileSuccessViewModel();
?>
<div class="checkout-success">
    <?php if ($block->getData('order_id')):?>
        <?php if ($block->getData('can_view_order')) :?>
            <ul>
                <li><span><?= /* @noEscape */ __('Order %1 placed', sprintf('<a href="%s" class="order-number"><strong>%s</strong></a>', $block->escapeHtml($block->getViewOrderUrl()), $block->escapeHtml($block->getOrderId()))) ?></span></li>
                <?php foreach ($profileSuccessViewModel->getProfileOrders() as $profileOrder): ?>
                    <li>
                        <span><?= /* @escapeNotVerified */ __('Subscription %1 created,', sprintf('<a href="%s" class="profile-number"><strong>%s</strong></a>', $block->escapeHtml($profileSuccessViewModel->getEditUrl($profileOrder)), $block->escapeHtml($profileSuccessViewModel->getEditLabel($profileOrder))))?></span>
                        <span><?= /* @escapeNotVerified */ __('next payment on '), $block->escapeHtml($profileSuccessViewModel->getNextPaymentDate($profileOrder->getSubscriptionProfileId())) ?></span>
                    </li>
                <?php endforeach; ?>
            </ul>
        <?php  else :?>
            <ul>
                <li><span><?= /* @noEscape */ __('Order %1 placed', $block->escapeHtml($block->getOrderId())) ?></span></li>
                <?php foreach ($profileSuccessViewModel->getProfileOrders() as $profileOrder): ?>
                    <li>
                        <span><?= /* @escapeNotVerified */ __('Subscription %1 created,', $block->escapeHtml($profileSuccessViewModel->getEditLabel($profileOrder))) ?></span>
                        <span><?= /* @escapeNotVerified */ __('next payment on '), $block->escapeHtml($profileSuccessViewModel->getNextPaymentDate($profileOrder->getSubscriptionProfileId())) ?></span>
                    </li>
                <?php endforeach; ?>
            </ul>
            <p></p>
        <?php endif;?>
        <p><?= /* @escapeNotVerified */ __('We\'ll email you an order confirmation with details and tracking info.') ?></p>
    <?php endif;?>

    <?= $block->getAdditionalInfoHtml() ?>

    <div class="actions-toolbar">
        <div class="primary">
            <a class="action primary continue" href="<?= /* @escapeNotVerified */ $block->getContinueUrl() ?>"><span><?= /* @escapeNotVerified */ __('Continue Shopping') ?></span></a>
        </div>
    </div>
</div>
