<?php
/**
 * Copyright © 2018 TechNWeb, Inc. All rights reserved.
 * See TNW_LICENSE.txt for license details.
 */
// @codingStandardsIgnoreFile

/**  @var $block Magento\Checkout\Block\Cart\Grid */
/**  @var $groupsViewModel TNW\Subscriptions\Block\Cart\Groups */
$groupsViewModel = $block->getGroupsViewModel();
?>
<?php $mergedCells = ($this->helper(Magento\Tax\Helper\Data::class)->displayCartBothPrices() ? 2 : 1); ?>
<?= $block->getChildHtml('form_before') ?>
<form action="<?= /* @escapeNotVerified */ $block->getUrl('checkout/cart/updatePost') ?>"
      method="post"
      id="form-validate"
      data-mage-init='{"Magento_Checkout/js/action/update-shopping-cart":
              {"validationURL" : "<?= $block->escapeUrl($block->getUrl('checkout/cart/updateItemQty')) ?>",
              "updateCartActionContainer": "#update_cart_action_container"}
          }'
      class="form form-cart">
    <?= $block->getBlockHtml('formkey') ?>
    <?php foreach ($groupsViewModel->getGroupQuoteItems() as $frequency_id => $groupItems) : ?>
    <div class="cart table-wrapper<?= $mergedCells == 2 ? ' detailed' : '' ?>">
        <?php if ($block->getPagerHtml()) :?>
            <div class="cart-products-toolbar cart-products-toolbar-top toolbar"
                 data-attribute="cart-products-toolbar-top"><?= $block->getPagerHtml() ?>
            </div>
        <?php endif ?>
        <h2><?= $block->escapeHtml($groupsViewModel->getCaption($groupItems, $frequency_id)) ?></h2>
        <table class="cart items data table"
               data-mage-init='{"shoppingCart":{"emptyCartButton": ".action.clear",
                   "updateCartActionContainer": "#update_cart_action_container"}}'>
            <caption class="table-caption">
                <?= $block->escapeHtml(__('Shopping Cart Items')) ?>
            </caption>
            <thead>
                <tr>
                    <th class="col item" scope="col"><span><?= $block->escapeHtml(__('Item')) ?></span></th>
                    <?php if (!$groupsViewModel->isSubscriptionItem(reset($groupItems))) : ?>
                    <th class="col price" scope="col"><span><?= $block->escapeHtml(__('Price')) ?></span></th>
                    <?php endif; ?>
                    <th class="col qty" scope="col"><span><?= $block->escapeHtml(__('Qty')) ?></span></th>
                    <th class="col subtotal" scope="col"><span><?= $block->escapeHtml(__('Subtotal')) ?></span></th>
                </tr>
            </thead>
                <tbody class="items">
                <?php foreach ($groupItems as $groupItem) : ?>
                    <?= $block->getItemHtml($groupItem) ?>
                <?php endforeach; ?>
                </tbody>
        </table>
    </div>
    <?php endforeach; ?>
    <div class="cart main actions">
        <button type="submit"
                name="update_cart_action"
                value="update_qty"
                title="<?= $block->escapeHtml(__('Update Shopping Cart')) ?>"
                class="action update">
            <span><?= /* @escapeNotVerified */ __('Update Shopping Cart') ?></span>
        </button>
    </div>
</form>
<?= $block->getChildHtml('checkout.cart.order.actions') ?>
<?= $block->getChildHtml('shopping.cart.table.after') ?>

