<?php
/**
 * Copyright © 2018 TechNWeb, Inc. All rights reserved.
 * See TNW_LICENSE.txt for license details.
 */

/** @var $block \TNW\Subscriptions\Block\Cart\Grid */
?>
<div id="cart-totals" class="cart-totals">
    <?php foreach ($block->groupQuoteItems() as $groupItems) : ?>
    <table class="data table totals">
        <caption class="table-caption">
            <h3><?= $block->escapeHtml($block->getCaption($groupItems)) ?></h3>
        </caption>
        <tfoot>
        <tr class="totals">
            <th class="mark"><?= $block->escapeHtml(__('Subtotal')) ?></th>
            <td class="amount">
                <?= /* @escapeNotVerified */ $block->getSubtotal($groupItems) ?>
            </td>
        </tr>
        </tfoot>
        <tbody>
        <?php foreach ($groupItems as $item) : ?>
        <tr class="totals">
            <th class="mark" colspan="2">
                <span class="label product-name">
                    <?= $block->getSubscribeQty($item) ?>
                    <a href="<?= /* @escapeNotVerified */ $block->getItemProductUrl($item) ?>">
                        <?= $block->escapeHtml($block->getItemName($item)) ?>
                    </a>
                </span>
            </th>
        </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
    <?php endforeach; ?>
</div>
