<?php
/**
 * Copyright © 2018 TechNWeb, Inc. All rights reserved.
 * See TNW_LICENSE.txt for license details.
 */
/**
 * @var $block \TNW\Subscriptions\Block\Subscription\Billing\EmailCouponInformation
 * @var $escaper \Magento\Framework\Escaper
 */
?>
<?php if ($block->getCouponCode()): ?>
    <?php if (!$block->isCouponValid()): ?>
        <table class="tnw-message-coupon-wrapper">
            <tbody>
            <tr>
                <td class="tnw-message-coupon-error">
                    <?= $escaper->escapeHtml(
                        __(
                            'Applied coupon "%1" is not eligible for this order and was skipped.',
                            $block->getCouponCode()
                        )
                    ); ?>
                </td>
            </tr>
            </tbody>
        </table>
    <?php endif; ?>
<?php endif; ?>
