<?php
/**
 * Copyright © 2018 TechNWeb, Inc. All rights reserved.
 * See TNW_LICENSE.txt for license details.
 */

/**
 * @var $block \Magento\Wishlist\Block\Customer\Sidebar
 * @var $escaper \Magento\Framework\Escaper
 */
?>
<?php
$wishlistHelper = $this->helper(\Magento\Wishlist\Helper\Data::class);
?>
<?php if ($wishlistHelper->isAllow()): ?>
    <div class="block block-wishlist" data-bind="scope: 'wishlist'">
        <div class="block-title">
            <strong><?= $escaper->escapeHtml($block->getTitle()) ?></strong>
            <!-- ko if: wishlist().counter -->
            <span data-bind="text: wishlist().counter" class="counter"></span>
            <!-- /ko -->
        </div>
        <div class="block-content">
            <strong class="subtitle"><?= $escaper->escapeHtml(__('Last Added Items')) ?></strong>
            <!-- ko if: wishlist().counter -->
                <ol class="product-items no-display" id="wishlist-sidebar"
                    data-bind="foreach: wishlist().items, css: {'no-display': null}">
                    <li class="product-item">
                        <div class="product-item-info">
                            <a class="product-item-photo" data-bind="attr: { href: product_url, title: product_name }">
                                <!-- ko template: {name: $data.image.template, data: $data.image} --><!-- /ko -->
                            </a>
                            <div class="product-item-details">
                                <strong class="product-item-name">
                                    <a data-bind="attr: { href: product_url }" class="product-item-link">
                                        <span data-bind="text: product_name"></span>
                                    </a>
                                </strong>
                                <!-- ko if: subs_top_message -->
                                <strong class="product-item-name" data-bind="html: subs_top_message"></strong>
                                <!-- /ko -->
                                <!-- ko if: subs_trial_price -->
                                <div class="price-box price-final_price">
                                    <span class="price-wrapper" data-role="priceBox">
                                        <span class="price" data-bind="html: subs_trial_price"></span>
                                    </span>
                                </div>
                                <!-- /ko -->
                                <!-- ko ifnot: subs_trial_price -->
                                <div data-bind="html: product_price"></div>
                                <!-- /ko -->
                                <div class="product-item-actions">
                                    <div class="actions-primary">
                                    <!-- ko if: product_is_saleable_and_visible -->
                                        <!-- ko if: is_subscribe && !is_one_time_purchase -->
                                            <!-- ko if: is_subscribe_only -->
                                            <div class="product-subscribe-button">
                                                <button type="button"
                                                        title="<?= $escaper->escapeHtml(__('Auto-Ship')) ?>"
                                                        data-bind="attr: {'data-post': subs_addtocart_params}"
                                                        class="action primary subscribe">
                                                        <span data-role="button-text">
                                                            <?= $escaper->escapeHtml(__('Auto-Ship')) ?>
                                                        </span>
                                                </button>
                                            </div>
                                            <!-- /ko -->
                                            <!-- ko ifnot: is_subscribe_only -->
                                            <div class="product-subscribe-addtocart-buttons-container"
                                                 data-bind="mageInit: {'tnwSubscribeListButtons':{}}">
                                                <div class="product-subscribe-button">
                                                    <button type="button"
                                                            title="<?= $escaper->escapeHtml(__('Auto-Ship')) ?>"
                                                            data-bind="attr: {'data-post': subs_addtocart_params}"
                                                            class="action primary subscribe">
                                                        <span data-role="button-text">
                                                            <?= $escaper->escapeHtml(__('Auto-Ship')) ?>
                                                        </span>
                                                    </button>
                                                </div>
                                                <div class="product-subscribe-button-dropdown">
                                                    <button title="<?= $escaper->escapeHtml(__('Add to Cart')) ?>"
                                                            class="action-toggle primary add"
                                                            data-toggle="dropdown"
                                                            data-bind="attr: {'data-wishlist-item-counter': $index()}">
                                                        <span><?= $escaper->escapeHtml(__('Select')) ?></span>
                                                    </button>
                                                </div>
                                                <div class="product-addtocart-button-hidden"
                                                     data-bind="css: 'subscription-dropdown-hidden-' + $index()">
                                                    <div class="actions-primary">
                                                        <!-- ko if: product_has_required_options -->
                                                        <a href="#" data-bind="attr: {'data-post': add_to_cart_params}"
                                                           class="action tocart primary">
                                                            <span><?= $escaper->escapeHtml(__('Add to Cart')) ?></span>
                                                        </a>
                                                        <!-- /ko -->
                                                        <!-- ko ifnot: product_has_required_options -->
                                                        <button type="button" class="action tocart primary"
                                                                data-bind="attr: {'data-post': add_to_cart_params}">
                                                            <span><?= $escaper->escapeHtml(__('Add to Cart')) ?></span>
                                                        </button>
                                                        <!-- /ko -->
                                                    </div>
                                                </div>
                                            </div>
                                            <!-- /ko -->
                                        <!-- /ko -->
                                        <!-- ko if: !is_subscribe || is_one_time_purchase  -->
                                            <!-- ko if: product_has_required_options -->
                                                <a href="#" data-bind="attr: {'data-post': add_to_cart_params}"
                                                   class="action tocart primary">
                                                    <span><?= $escaper->escapeHtml(__('Add to Cart')) ?></span>
                                                </a>
                                            <!-- /ko -->
                                            <!-- ko ifnot: product_has_required_options -->
                                                <button type="button" class="action tocart primary"
                                                        data-bind="attr: {'data-post': add_to_cart_params}">
                                                    <span><?= $escaper->escapeHtml(__('Add to Cart')) ?></span>
                                                </button>
                                            <!-- /ko -->
                                        <!-- /ko -->
                                    <!-- /ko -->
                                    </div>
                                    <div class="actions-secondary">
                                        <a href="#"  data-bind="attr: {'data-post': delete_item_params}"
                                           title="<?= $escaper->escapeHtml(__('Remove This Item')) ?>"
                                           class="btn-remove action delete">
                                            <span><?= $escaper->escapeHtml(__('Remove This Item')) ?></span>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </li>
                </ol>
                <div class="actions-toolbar no-display" data-bind="css: {'no-display': null}">
                    <div class="primary">
                        <a class="action details"
                           href="<?= $escaper->escapeHtml($wishlistHelper->getListUrl()) ?>"
                           title="<?= $escaper->escapeHtml(__('Go to Wish List')) ?>">
                            <span><?= $escaper->escapeHtml(__('Go to Wish List')) ?></span>
                        </a>
                    </div>
                </div>
            <!-- /ko -->
            <!-- ko ifnot: wishlist().counter -->
                <div class="empty"><?= $escaper->escapeHtml(__('You have no items in your wish list.')) ?></div>
            <!-- /ko -->
        </div>
    </div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "wishlist": {
                        "component": "Magento_Wishlist/js/view/wishlist"
                    }
                }
            }
        }
    }
</script>
<?php endif ?>
