<?php
/**
 * Copyright © 2018 TechNWeb, Inc. All rights reserved.
 * See TNW_LICENSE.txt for license details.
 */

/* @var $block \TNW\Subscriptions\Block\Product\View\Subscribe */
?>

<?php if ($block->isSubscribeAvailable()): ?>
    <?php if ($block->IsOnlySubscribePurchase()): ?>
        <input type="hidden" name="subscribe_active" value="1" />
        <div class="addtocart-tabs" data-mage-init='{"tabs":{"openedState":"active"}}'>
            <div class="title-container">
                <div class="tab-title" data-role="collapsible" tabindex="0">
                    <a href="#subscribe-tab">
                        <?php /* @escapeNotVerified */ echo __('Subscribe') ?>
                    </a>
                </div>
            </div>
            <div class="content-container">
                <div class="tab-content subscribe-tab" id="subscribe-tab" data-role="content">
                    <?php echo $block->getChildHtml('addtocart_subscribe') ?>
                </div>
            </div>
        </div>
        <script type="text/x-magento-init">
            {
                "#product_addtocart_form": {
                    "Magento_Catalog/js/validate-product": {}
                }
            }
        </script>
    <?php elseif ($block->IsOneTimeAndSubscribePurchase()): ?>
        <input type="hidden" name="subscribe_active" value="1" />
        <div class="addtocart-tabs" data-mage-init='{"tabs":{"openedState":"active"}}'>
            <div class="title-container">
                <div class="tab-title" id="subscribe-tab-head" data-role="collapsible" tabindex="0">
                    <a href="#subscribe-tab">
                        <?php /* @escapeNotVerified */ echo __('Subscribe') ?>
                    </a>
                </div>
                <div class="tab-title" id="addtocart-tab-head" data-role="collapsible" tabindex="1">
                    <a href="#addtocart-tab">
                        <?php /* @escapeNotVerified */ echo __('One Time Purchase') ?>
                    </a>
                </div>
            </div>
            <div class="content-container">
                <div class="tab-content subscribe-tab" id="subscribe-tab" data-role="content">
                    <?php echo $block->getChildHtml('addtocart_subscribe') ?>
                </div>
                <div class="tab-content" id="addtocart-tab" data-role="content" style="display:none">
                    <?php echo $block->getChildHtml('addtocart_orig') ?>
                </div>
            </div>
        </div>
    <?php else: ?>
        <input type="hidden" name="subscribe_active" value="0" />
        <?php echo $block->getChildHtml('addtocart_orig') ?>
    <?php endif ?>
<?php else: ?>
    <input type="hidden" name="subscribe_active" value="0" />
    <?php echo $block->getChildHtml('addtocart_orig') ?>
<?php endif ?>
