<?php
/**
 * Copyright © 2018 TechNWeb, Inc. All rights reserved.
 * See TNW_LICENSE.txt for license details.
 */

/**
 * @var $block \TNW\Subscriptions\Block\Product\View\Subscribe
 * @var $escaper \Magento\Framework\Escaper
 */
?>
<?php if ($block->isAllowedAddToCart()): ?>
    <?php if ($block->isSubscribeAvailable()): ?>
        <?php if ($block->isOnlySubscribePurchase()): ?>
            <input type="hidden" name="subscribe_active" value="1" />
            <div class="tnw-addtocart-container">
                <div class="addtocart-subscribe">
                    <div class="box-tocart">
                        <input type="hidden" name="addtocart_type" value="1"/>
                        <?= $block->getChildHtml('addtocart_subscribe') ?>
                    </div>
                </div>
            </div>
    <?php elseif ($block->isOneTimeAndSubscribePurchase()): ?>
        <input type="hidden" name="subscribe_active" value="<?= $block->isSubscriptionDefault() ? 1 : 0 ?>" />
        <div class="tnw-addtocart-container">
            <div class="addtocart-onetime">
                <input type="radio" id="addtocart_onetime"
                       name="addtocart_type" value="0"
                    <?= $block->isSubscriptionDefault() ?: 'checked' ?>
                />
                <label for="addtocart_onetime"><?= $escaper->escapeHtml(__('Purchase')) ?></label>
                <div class="onetime-final-price"></div>
                <div class="addtocart-wrapper">
                    <?= $block->getChildHtml('addtocart_orig') ?>
                </div>
            </div>
            <div class="addtocart-subscribe">
                <div class="box-tocart">
                    <input type="radio" id="addtocart_subscribe"
                           name="addtocart_type" value="1"
                        <?= $block->isSubscriptionDefault() ? 'checked' : '' ?>
                    />
                    <label for="addtocart_subscribe"><?= $escaper->escapeHtml(__('Auto-Ship')) ?></label>
                    <div class="subscription-price-with-savings"></div>
                    <div class="addtocart-wrapper">
                        <?= $block->getChildHtml('addtocart_subscribe') ?>
                    </div>
                </div>
            </div>
        </div>
        <?php else: ?>
            <input type="hidden" name="subscribe_active" value="0" />
            <?= $block->getChildHtml('addtocart_orig') ?>
        <?php endif ?>
    <?php else: ?>
        <input type="hidden" name="subscribe_active" value="0" />
        <?= $block->getChildHtml('addtocart_orig') ?>
    <?php endif ?>
<?php elseif (!$block->isOnlySubscribePurchase()): ?>
    <input type="hidden" name="subscribe_active" value="0" />
    <?= $block->getChildHtml('addtocart_orig') ?>
<?php else: ?>
    <input type="hidden" name="subscribe_active" value="0" />
    <div class="product-unavailable">
        <?= $escaper->escapeHtml(__('Product is not available for purchase at this time'))?>
    </div>
<?php endif ?>
