<?php
/**
 * Copyright © 2017 TechNWeb, Inc. All rights reserved.
 * See TNW_LICENSE.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var TNW\Subscriptions\Block\Adminhtml\SubscriptionProfile\Edit\Dashboard\Profit $block */
?>

<div class="admin__fieldset profit-content">
    <div class="admin__profile-dashboard-profit-diagram">
    <!--todo: add actual diagram.-->
    </div>
    <div class="admin__profile-dashboard-profit-diagram-legend">
        <div class="admin__profile-dashboard-profit-diagram-legend-text">
            <div class="profit-color profit-for-today-color"></div>
            <span class="profit-text"><?php echo  __('%1 as of today', $block->getAsOfTodayProfit())?></span>
        </div>
        <?php if (!$block->getHideRemainingProfit()): ?>
        <div class="admin__profile-dashboard-profit-diagram-legend-text">
            <div class="profit-color profit-remaining-color"></div>
            <span class="profit-text"><?php echo  __('%1 remaining', $block->getRemainingProfit())?></span>
        </div>
        <?php endif ?>
    </div>
</div>
<?php if (!$block->getHideRemainingProfit()): ?>
<span class="admin__field-note"><?php echo __('* The graph above accounts for 1 product(s) from the subscription with total of 1 product(s)') ?></span>
<?php endif ?>

