<?php
/**
 * Copyright © 2017 TechNWeb, Inc. All rights reserved.
 * See TNW_LICENSE.txt for license details.
 */

/* @var $block \TNW\Subscriptions\Block\Cart\Link */

// @codingStandardsIgnoreFile
?>
<div data-role="tnw-subscriptions-cart-link"  data-bind="scope: 'subscriptionCart'" class="tnw-subscriptions-cart-link__container">
    <a class="tnw-subscriptions-cart-link no-display"
       href="<?php echo $block->escapeUrl($block->getCartUrl()) ?>"
       title="<?php /* @noEscape */ echo __('Subscription Cart') ?>"
       data-bind="css: {'no-display': !subscriptionCart().itemsCount}"
    >

    <img src="<?php /* @noEscape */ echo $block->getViewFileUrl('TNW_Subscriptions/images/cart-link.svg'); ?>"
             width="24"
             height="24">
        <span data-bind="text: subscriptionCart().itemsCount"></span>
    </a>
</div>
<script type="text/x-magento-init">
    {
        "[data-role=tnw-subscriptions-cart-link]": {
            "Magento_Ui/js/core/app": <?php /* @noEscape */ echo $block->getJsLayout();?>
        }
    }
</script>
