<?php
/**
 * Copyright © 2017 TechNWeb, Inc. All rights reserved.
 * See TNW_LICENSE.txt for license details.
 */

/* @var $block \TNW\Subscriptions\Block\Cart */

// @codingStandardsIgnoreFile
?>

<?php if ($block->getCartItemsCount()): ?>
    <div id="tnw-subscriptions-cart" data-role="loader-container" data-bind="scope:'cart'" class="tnw-subscriptions-cart-container">
        <div id="tnw-subscriptions-loader" data-role="cart-loader" class="loading-mask" data-mage-init='{"checkoutLoader": {}}'>
            <div class="loader">
                <img src="<?php echo $block->escapeUrl($block->getViewFileUrl('images/loader-1.gif')) ?>"
                     alt="<?php /* @noEscape */ echo __('Loading...') ?>"
                     style="position: absolute;">
            </div>
        </div>
        <!-- ko template: getTemplate() --><!-- /ko -->
        <script type="text/x-magento-init">
            {
                "#tnw-subscriptions-cart": {
                    "Magento_Ui/js/core/app": <?php /* @noEscape */ echo $block->getJsLayout();?>
                }
            }
        </script>
        <script>
            window.tnwSubscriptionsCheckoutConfig = <?php /* @noEscape */ echo \Zend_Json::encode
            ($block->getCheckoutConfig()); ?>;
        </script>
    </div>
<?php else: ?>
    <div class="cart-empty">
        <p><?php echo $block->escapeHtml(__('You have no items in your subscription cart.')) ?></p>
        <p><?php /* @escapeNotVerified */ echo __('Click <a href="%1">here</a> to continue shopping.',
                $block->escapeUrl($block->getContinueShoppingUrl())) ?></p>
    </div>
<?php endif; ?>
<script>
    window.checkout = <?php /* @escapeNotVerified */ echo \Zend_Json::encode($block->getConfig()); ?>;
</script>
