<?php
/**
 * Copyright © 2018 TechNWeb, Inc. All rights reserved.
 * See TNW_LICENSE.txt for license details.
 */

/** @var $block \TNW\Subscriptions\Block\Checkout */
?>
<div id="tnw-subscriptions-cart" data-role="loader-container" data-bind="scope:'cart'" class="tnw-subscriptions-cart-container">
    <div id="tnw-subscriptions-loader" data-role="cart-loader" class="loading-mask" data-mage-init='{"checkoutLoader": {}}'>
        <div class="loader">
            <img src="<?php echo $block->escapeUrl($block->getViewFileUrl('images/loader-1.gif')) ?>"
                 alt="<?php /* @noEscape */ echo __('Loading...') ?>"
                 style="position: absolute;">
        </div>
    </div>
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
        {
            "#tnw-subscriptions-cart": {
                "Magento_Ui/js/core/app": <?php /* @noEscape */ echo $block->getJsLayout();?>
            }
        }
    </script>
</div>
<script>
    window.customerData = [];
    require([
        'Magento_Ui/js/block-loader'
    ], function(blockLoader) {
        blockLoader("<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/loader-1.gif'); ?>");
    })
</script>