<?php
/**
 * Copyright © 2017 TechNWeb, Inc. All rights reserved.
 * See TNW_LICENSE.txt for license details.
 */

/* @var $block \TNW\Subscriptions\Block\JsLayout */

// @codingStandardsIgnoreFile
?>
<script type="text/x-magento-init">
            {
                "#tnw-subscriptions-cart": {
                    "Magento_Ui/js/core/app": <?php /* @noEscape */echo $block->getJsLayout(); ?>
                }
            }
</script>