<?php
/**
 *  Copyright © 2017 TechNWeb, Inc. All rights reserved.
 *  See TNW_LICENSE.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<?php
/** @var \TNW\Subscriptions\Pricing\Render\SubConfigurablePriceBox $block */

$productId = $block->getSaleableItem()->getId();

/** @var \Magento\Framework\Pricing\Price\PriceInterface $finalPriceModel */
$finalPriceModel = $block->getPriceType('final_price');
$idSuffix = $block->getIdSuffix() ? $block->getIdSuffix() : '';
$schema = ($block->getZone() == 'item_view') ? true : false;
?>
<?php /* @escapeNotVerified */ $data = $block->renderSubscriptionAmounts(
    $finalPriceModel->getAmount(),
    $block->getProduct(),
    [
        'price_id'          => $block->getPriceId('product-price-' . $idSuffix),
        'price_type'        => 'finalPrice',
        'include_container' => true,
        'schema' => $schema,
    ]
);
$data = $block->getEncodedData($data);
?>
<script type="text/x-magento-init">
{
    "*": {
        "tnwSubConfigurablePrice": {
            "subscriptionPricesData" : <?php echo $data ?>,
            "productAttributesData" : <?php echo $block->getEncodedData($block->getOptions())?>,
            "subBillingFrequencyId" : <?php echo $block->getBillingFrequencyId() ?>
        }
    }
}
</script>
