<?php
/**
 *  Copyright © 2017 TechNWeb, Inc. All rights reserved.
 *  See TNW_LICENSE.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<?php
/** @var \TNW\Subscriptions\Pricing\Render\SubscriptionPriceBox $block */

$productId = $block->getSaleableItem()->getId();

/** ex: \Magento\Catalog\Pricing\Price\RegularPrice */
/** @var \Magento\Framework\Pricing\Price\PriceInterface $priceModel */
$priceModel = $block->getPriceType('regular_price');

/** ex: \Magento\Catalog\Pricing\Price\FinalPrice */
/** @var \Magento\Framework\Pricing\Price\PriceInterface $finalPriceModel */
$finalPriceModel = $block->getPriceType('final_price');
$idSuffix = $block->getIdSuffix() ? $block->getIdSuffix() : '';
$schema = ($block->getZone() == 'item_view') ? true : false;
?>
<?php /* @escapeNotVerified */ $data = $block->renderSubscriptionAmounts($finalPriceModel->getAmount(), [
    'price_id'          => $block->getPriceId('product-price-' . $idSuffix),
    'price_type'        => 'finalPrice',
    'include_container' => true,
    'schema' => $schema,
]); ?>
<script type="text/x-magento-init">
{
    "*": {
        "tnwSubscribePrice": {
            "subscriptionPricesData" : <?php echo $data ?>
        }
    }
}
</script>
