<?php
/**
 * Copyright © 2018 TechNWeb, Inc. All rights reserved.
 * See TNW_LICENSE.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \TNW\Subscriptions\Block\Adminhtml\SubscriptionProfile\Edit\Summary\AccountInformation $block */
?>
<div class="admin__profile-summary-account-information">
    <div class="fieldset">
        <div class="subscription-summary">
            <table class="admin__table-secondary data-table">
                <tbody>
                <tr class="col-0">
                    <td class="label"><?= __("Status") ?></td>
                    <td><span class="text"><?= $block->getStatus() ?></span></td>
                </tr>
                <tr class="col-1">
                    <td class="label"><?= __('Created On') ?></td>
                    <td><span class="date"><?= $block->getCreatedOn() ?></span></td>
                </tr>
                <tr class="col-2">
                    <td class="label"><?= __('Last Successful Order') ?></td>
                    <td><span class="date"><?= $block->getLastSuccessfulOrder() ?></span></td>
                </tr>
                <tr class="col-3">
                    <td class="label"><?= __('Trial Ends On') ?></td>
                    <td><span class="date"><?= $block->getTrialEndsOn() ?></span></td>
                </tr>
                <tr class="col-4">
                    <td class="label"><?= __('Subscription Ends On') ?></td>
                    <td><span class="date"><?= $block->getSubscriptionEndsOn() ?></span></td>
                </tr>
                </tbody>
            </table>
        </div>
        <div class="summary-account-information">
            <table class="admin__table-secondary data-table">
                <tbody>
                <tr class="col-0">
                    <td class="label"><?= __("Customer Name") ?></td>
                    <td><span class="text"><a href="<?= $this->getCustomerUrl(); ?>" ><?= $block->getCustomerName() ?></a></span></td>
                </tr>
                <tr class="col-1">
                    <td class="label"><?= __('Email') ?></td>
                    <td><span class="text">
                            <a href="mailto:<?= $block->getEmail() ?>"><?= $block->getEmail() ?></a>
                        </span>
                    </td>
                </tr>
                <tr class="col-2">
                    <td class="label"><?= __('Customer Group') ?></td>
                    <td><span class="text"><?= $block->getCustomerGroup() ?></span></td>
                </tr>
                <tr class="col-3">
                    <td class="label"><?= __('Currency') ?></td>
                    <td><span class="text"><?= $block->getCurrency() ?></span></td>
                </tr>
                <tr class="col-4">
                    <td class="label"><?= __('Website') ?></td>
                    <td><span class="text"><?= $block->getWebsite() ?></span></td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
