<?php
/**
 * Copyright © 2018 TechNWeb, Inc. All rights reserved.
 * See TNW_LICENSE.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \TNW\Subscriptions\Block\Adminhtml\SubscriptionProfile\Edit\Summary\AccountInformation $block */
?>
<div class="admin__profile-summary-account-information">
    <div class="fieldset">
        <div class="subscription-summary">
            <table class="admin__table-secondary data-table">
                <tbody>
                <tr class="col-0">
                    <td class="label"><?= /* @noEscape */ __("Status") ?></td>
                    <td><span class="text"><?= /* @noEscape */ $block->getStatus() ?></span></td>
                </tr>
                <tr class="col-1">
                    <td class="label"><?= /* @noEscape */ __('Created On') ?></td>
                    <td><span class="date"><?= /* @noEscape */ $block->getCreatedOn() ?></span></td>
                </tr>
                <tr class="col-2">
                    <td class="label"><?= /* @noEscape */ __('Last Successful Order') ?></td>
                    <td><span class="date"><?= /* @noEscape */ $block->getLastSuccessfulOrder() ?></span></td>
                </tr>
                <tr class="col-3">
                    <td class="label"><?= /* @noEscape */ __('Trial Ends On') ?></td>
                    <td><span class="date"><?= /* @noEscape */ $block->getTrialEndsOn() ?></span></td>
                </tr>
                <tr class="col-4">
                    <td class="label"><?= /* @noEscape */ __('Subscription Ends On') ?></td>
                    <td><span class="date"><?= /* @noEscape */ $block->getSubscriptionEndsOn() ?></span></td>
                </tr>
                </tbody>
            </table>
        </div>
        <div class="summary-account-information">
            <table class="admin__table-secondary data-table">
                <tbody>
                <tr class="col-0">
                    <td class="label"><?= /* @noEscape */ __("Customer Name") ?></td>
                    <td><span class="text"><a href="<?= /* @noEscape */ $this->getCustomerUrl(); ?>" ><?= /* @noEscape */ $block->getCustomerName() ?></a></span></td>
                </tr>
                <tr class="col-1">
                    <td class="label"><?= /* @noEscape */ __('Email') ?></td>
                    <td><span class="text">
                            <a href="mailto:<?= /* @noEscape */ $block->getEmail() ?>"><?= /* @noEscape */ $block->getEmail() ?></a>
                        </span>
                    </td>
                </tr>
                <tr class="col-2">
                    <td class="label"><?= /* @noEscape */ __('Customer Group') ?></td>
                    <td><span class="text"><?= /* @noEscape */ $block->getCustomerGroup() ?></span></td>
                </tr>
                <tr class="col-3">
                    <td class="label"><?= /* @noEscape */ __('Currency') ?></td>
                    <td><span class="text"><?= /* @noEscape */ $block->getCurrency() ?></span></td>
                </tr>
                <tr class="col-4">
                    <td class="label"><?= /* @noEscape */ __('Website') ?></td>
                    <td><span class="text"><?= /* @noEscape */ $block->getWebsite() ?></span></td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
