<?php /* @var \TNW\Subscriptions\Block\Subscription\Summary\Overview $block */ ?>
<div class="overview-content">
    <table class="overview-table" style="width:100%">
        <tr style="height:25%;">
            <?php if ($block->getCanShowNextPayment()): ?>
            <td rowspan="2" class="next-payment"><?= $block->getNextPaymentHtml() ?></td>
            <?php endif ?>
            <td colspan="2" class="bordered subscription-message <?= /* @noEscape */ $block->getBlockMessage()->getStatusClass() ?>"><?= $block->getMessageHtml() ?></td>
        </tr>
        <tr>
            <td style="width:33%" class="bordered missed-payments"><?= $block->getMissedPaymentsHtml() ?></td>
            <td style="width:33%" class="bordered status <?= /* @noEscape */ $block->getBlockStatus()->getStatusClass() ?>"><?= $block->getStatusHtml() ?></td>
        </tr>
    </table>
</div>
