<?php
/**
 * Copyright © 2017 TechNWeb, Inc. All rights reserved.
 * See TNW_LICENSE.txt for license details.
 */
?>
<?php /* @var \TNW\Subscriptions\Block\Subscription\Summary\Products\Configurable $block */ ?>
<?php $options = $block->getItemOptions()?>
<dl class="item-options config-item-options">
<?php foreach ($options as $option) : ?>
    <dt><?php echo $block->escapeHtml($option['attributeLabel']) ?></dt>
    <dd><?php echo $block->escapeHtml($option['optionLabel']) ?></dd>
<?php endforeach; ?>
</dl>
