<?php
/**
 * Copyright © 2018 TechNWeb, Inc. All rights reserved.
 * See TNW_LICENSE.txt for license details.
 */

/* @var $block \TNW\Subscriptions\Block\Product\View\Subscribe */
?>
<?php
$block->getProduct()->setPriceCalculation();
$_item = $block->getItem();
$_itemId = $_item->getId();
$groupsViewModel = $block->getParentBlock()->getGroupsViewModel();
?>
<?php if ($block->isSubscribeAvailable()) : ?>
    <?php if ($block->IsOneTimeAndSubscribePurchase()): ?>
    <div class="product-item-subscription-details">
        <input type="hidden" name="subscribe_active" value="1" />
        <div class="tnw-addtocart-container">
            <div class="addtocart-subscribe">
                <input type="radio"
                       id="cart-<?= $_itemId; ?>-subscribe"
                       name="cart[<?= $_itemId; ?>][subscribe_active]"
                       value="1"
                    <?php if ($groupsViewModel->isSubscriptionItem($_item)): ?>
                        checked="checked"
                    <?php endif; ?>
                />
                <label for="cart-<?= $_itemId; ?>-subscribe"><?php /* @escapeNotVerified */ echo __('Subscribe') ?></label>
                <div class="addtocart-wrapper">
                    <div class="subscribe-container">
                        <div class="fieldset">
                            <div class="field required">
                                <label class="label"><span><?php echo __('Billing Frequency') ?>:</span></label>
                                <select name="cart[<?= $_itemId; ?>][billing_frequency]"
                                        id="cart[<?= $_itemId; ?>][billing_frequency]"
                                        class="required">
                                    <?php foreach ($block->getFrequencyOptions() as $option): ?>
                                        <option id="billing_frequency_<?php echo $option['value'] ?>"
                                                value="<?php echo $option['value'] ?>"
                                            <?php if ($option['is_default']): ?>
                                                selected
                                            <?php endif ?>
                                            <?php if (isset($option['preset_qty'])): ?>
                                                data-preset-qty="<?php echo $option['preset_qty'] * 1 ?>"
                                            <?php endif ?>
                                            <?php if (isset($option['frequency_unit'])): ?>
                                                data-frequency-unit="<?php echo $option['frequency_unit'] * 1 ?>"
                                            <?php endif ?>
                                            <?php if (isset($option['frequency_unit_type'])): ?>
                                                data-frequency-unit-type="<?php echo $option['frequency_unit_type'] * 1 ?>"
                                            <?php endif ?>
                                                data-default-label="
                                            <?php echo $option['label'] ?>
                                            <?php if ($option['is_default']): ?>
                                            &nbsp;<?php echo __('(most common)'); ?>
                                            <?php endif ?>"
                                        >
                                            <?php echo $option['label'] ?>
                                            <?php if ($option['is_default']): ?>
                                                &nbsp;<?php echo __('(most common)'); ?>
                                            <?php endif ?>
                                        </option>
                                    <?php endforeach ?>
                                </select>
                            </div>
                        </div>
                        <div class="fieldset">
                            <div class="field term required">
                                <label class="label"><span><?php echo __('Term') ?>:</span></label>
                                <div class="control">
                                    <?php if ($block->getIsInfiniteSubscriptions()): ?>
                                        <span><?php echo __('Until canceled') ?></span>
                                        <input type="hidden"
                                               name="cart[<?= $_itemId ?>][term]"
                                               class="input-text qty"
                                               data-validate='{"required-number":true}'
                                               value="1"
                                               checked="checked"
                                        />
                                        <input type="hidden"
                                               name="cart[<?= $_itemId ?>][period]"
                                               id="cart-<?= $_itemId ?>-period"
                                               class="input-text qty"
                                               data-validate='{"required-number":true}'
                                               value="<?php echo $block->getDefaultPeriod() ?>"
                                        />
                                    <?php else: ?>
                                        <div>
                                            <input type="radio"
                                                   id="cart-<?= $_itemId ?>-term1"
                                                   name="cart[<?= $_itemId ?>][term]"
                                                   value="1"
                                                <?php if ($block->getDefaultUntilCancelled()): ?>
                                                    checked="checked"
                                                <?php endif ?>
                                            />
                                            <label class="label" for="cart-<?= $_itemId ?>-term1">
                                                <span><?php echo __('Until canceled') ?></span>
                                            </label>
                                        </div>
                                        <div>
                                            <input type="radio"
                                                   id="cart-<?= $_itemId ?>-term0"
                                                   name="cart[<?= $_itemId ?>][term]"
                                                   value="0"
                                            />
                                            <label class="label" for="cart-<?= $_itemId ?>-term0">
                                                <span><?php echo __('Stop after') ?></span>
                                                <input type="number"
                                                       name="cart[<?= $_itemId ?>][period]"
                                                       id="cart-<?= $_itemId ?>-period"
                                                       class="input-text qty"
                                                       data-validate='{"required-number":true}'
                                                       value="<?php echo $block->getDefaultPeriod() ?>"
                                                >
                                                <span><?php echo __('payment(s)') ?></span>
                                            </label>
                                        </div>
                                    <?php endif;?>
                                </div>
                            </div>
                        </div>
                        <?php if ($block->getIsVisibleStartOn()): ?>
                            <div class="fieldset">
                                <div class="field date required">
                                    <label class="label"><span><?php echo __('Delivery Schedule') ?>:</span></label>
                                    <div class="control delivery-schedule">
                                        <span><?php echo __('First delivery on'); ?></span>
                                        <span class="cart-<?= $_itemId ?>-delivery-schedule-date"></span>
                                        <input type="hidden"
                                               name="cart[<?= $_itemId ?>][start_on_alt]"
                                               id="cart-<?= $_itemId ?>-start_on_alt"
                                        />
                                        <a href="#" class="action change-delivery-date"><?php echo __('change') ?></a>
                                        <span class="start-on-wrapper hidden">
                                            <input type="text"
                                                   name="cart[<?= $_itemId ?>][start_on]"
                                                   id="cart-<?= $_itemId ?>-start_at"
                                                   class="required"
                                                   value="<?php echo $block->getDefaultStartOn() ?>"
                                            />
                                            <a href="#" class="action update-delivery-date"><?php echo __('Update') ?></a>
                                        </span>
                                    </div>
                                </div>
                            </div>
                        <?php endif ?>
                    </div>
                    <?php if ($block->getIsVisibleStartOn()): ?>
                        <script type="text/javascript">
                            require([
                                "jquery",
                                "mage/calendar"
                            ], function($) {
                                $("#cart-<?= $_itemId ?>-start_at").calendar({
                                    showsTime: false,
                                    dateFormat: "<?php echo $block->getDateFormat() ?>",
                                    buttonImage: "<?php echo $block->getViewFileUrl('Magento_Theme::calendar.png') ?>",
                                    buttonText: "<?php echo __('Select Date') ?>",
                                    showOn: 'both',
                                    minDate: "<?php echo $block->getMinStartOn() ?>",
                                    altField: "#cart-<?= $_itemId ?>-start_on_alt",
                                    altFormat: "MM dd"
                                }).datepicker('setDate', '<?php echo $block->getDefaultStartOn() ?>');
                                $('.cart-<?= $_itemId ?>-delivery-schedule-date').html($('#cart-<?= $_itemId ?>-start_on_alt').val());
                            });
                        </script>
                    <?php endif ?>
                </div>
            </div>
            <div class="addtocart-onetime">
                <input type="radio"
                       id="cart-<?= $_itemId; ?>-onetime"
                       name="cart[<?= $_itemId; ?>][subscribe_active]"
                       value="0"
                    <?php if (!$groupsViewModel->isSubscriptionItem($_item)): ?>
                        checked="checked"
                    <?php endif; ?>
                />
                <label for="cart-<?= $_itemId; ?>-onetime"><?php /* @escapeNotVerified */ echo __('One Time Purchase') ?></label>
            </div>
        </div>
    </div>
    <?php elseif ($block->IsOnlySubscribePurchase()) : ?>

    <?php endif; ?>
<?php endif; ?>
