<?php
/**
 * Copyright © 2018 TechNWeb, Inc. All rights reserved.
 * See TNW_LICENSE.txt for license details.
 */

/**
 * @var $block \TNW\Subscriptions\Block\Product\View\Subscribe
 * @var $escaper \Magento\Framework\Escaper
 */
?>
<?php
$block->getProduct()->setPriceCalculation();
$_item = $block->getItem();
$_itemId = $_item->getId();
$groupsViewModel = $block->getParentBlock()->getGroupsViewModel();
$configurableOptions = $block->getPreconfiguredOptions();
$customOptions = $block->getPreconfiguredCustomOptions();
?>
<?php if ($block->isSubscribeAvailable()): ?>
    <?php if ($block->isOneTimeAndSubscribePurchase() || $block->isOnlySubscribePurchase()): ?>
    <div class="product-item-subscription-details">
        <div class="tnw-addtocart-container">
            <input type="hidden" name="cart[<?= /* @noEscape */ $_itemId; ?>][addtocart_type]" value="1"/>
            <?php if (is_array($configurableOptions)): ?>
                <?php foreach ($configurableOptions as $attributeId => $attributeValue): ?>
                    <input type="hidden"
                           name="cart[<?= /* @noEscape */ $_itemId; ?>][super_attribute][<?= /* @noEscape */ $attributeId; ?>]"
                           value="<?= /* @noEscape */ $attributeValue; ?>"
                    >
                <?php endforeach; ?>
            <?php endif; ?>
            <?php if (is_array($customOptions)): ?>
                <?php foreach ($customOptions as $optionId => $optionValue): ?>
                    <?php if (is_array($optionValue)): ?>
                        <?php foreach ($optionValue as $checkboxValue): ?>
                        <input type="hidden"
                               name="cart[<?= /* @noEscape */ $_itemId; ?>][options][<?= /* @noEscape */ $optionId; ?>][]"
                               value="<?= /* @noEscape */ $checkboxValue; ?>"
                        >
                        <?php endforeach; ?>
                    <?php else: ?>
                        <input type="hidden"
                               name="cart[<?= /* @noEscape */ $_itemId; ?>][options][<?= /* @noEscape */ $optionId; ?>]"
                               value="<?= /* @noEscape */ $optionValue; ?>"
                            >
                    <?php endif; ?>
                <?php endforeach; ?>
            <?php endif; ?>
            <div class="addtocart-subscribe">
                <input
                    <?php if ($block->isOnlySubscribePurchase()): ?>
                       type="hidden"
                    <?php else: ?>
                       type="radio"
                    <?php endif; ?>
                       id="cart-<?= /* @noEscape */ $_itemId; ?>-subscribe"
                       name="cart[<?= /* @noEscape */ $_itemId; ?>][subscribe_active]"
                       value="1"
                    <?php if ($groupsViewModel->isSubscriptionItem($_item)): ?>
                        checked="checked"
                    <?php endif; ?>
                />
                <label for="cart-<?= /* @noEscape */ $_itemId; ?>-subscribe">
                    <?= $escaper->escapeHtml(__('Auto-Ship')) ?>
                </label>
                <div class="addtocart-wrapper">
                    <div class="subscribe-container">
                        <div class="fieldset">
                            <div class="field">
                                <label class="label">
                                    <span><?= $escaper->escapeHtml(__('Billing Frequency')) ?>:</span>
                                </label>
                                <select name="cart[<?= /* @noEscape */ $_itemId; ?>][billing_frequency]"
                                        id="cart[<?= /* @noEscape */ $_itemId; ?>][billing_frequency]">
                                    <?php foreach ($block->getFrequencyOptions() as $option): ?>
                                        <option id="billing_frequency_<?= /* @noEscape */ $option['value'] ?>"
                                                value="<?= /* @noEscape */ $option['value'] ?>"
                                            <?php if ($option['is_default']): ?>
                                                selected
                                            <?php endif ?>
                                            <?php if (isset($option['preset_qty'])): ?>
                                                data-preset-qty="<?= $option['preset_qty'] * 1 ?>"
                                            <?php endif ?>
                                            <?php if (isset($option['frequency_unit'])): ?>
                                                data-frequency-unit="<?= $option['frequency_unit'] * 1 ?>"
                                            <?php endif ?>
                                            <?php if (isset($option['frequency_unit_type'])): ?>
                                                data-frequency-unit-type="<?= $option['frequency_unit_type'] * 1 ?>"
                                            <?php endif ?>
                                        >
                                            <?= $escaper->escapeHtml($option['label']) ?>
                                        </option>
                                    <?php endforeach ?>
                                </select>
                            </div>
                        </div>
                        <div class="fieldset">
                            <div class="field term">
                                <label class="label"><span><?= $escaper->escapeHtml(__('Term')) ?>:</span></label>
                                <div class="control">
                                    <?php if ($block->getIsInfiniteSubscriptions()): ?>
                                        <span><?= $escaper->escapeHtml(__('Until canceled')) ?></span>
                                        <input type="hidden"
                                               name="cart[<?= /* @noEscape */ $_itemId ?>][term]"
                                               class="input-text qty"
                                               data-validate='{"required-number":true}'
                                               value="1"
                                               checked="checked"
                                        />
                                        <input type="hidden"
                                               name="cart[<?= /* @noEscape */ $_itemId ?>][period]"
                                               id="cart-<?= /* @noEscape */ $_itemId ?>-period"
                                               class="input-text qty"
                                               data-validate='{"required-number":true, "validate-number-range":"2-9999999999"}'
                                               value="<?= /* @noEscape */ $block->getDefaultPeriod() ?>"
                                        />
                                    <?php else: ?>
                                        <div>
                                            <input type="radio"
                                                   id="cart-<?= /* @noEscape */ $_itemId ?>-term1"
                                                   name="cart[<?= /* @noEscape */ $_itemId ?>][term]"
                                                   value="1"
                                                <?php if ($block->getDefaultUntilCancelled()): ?>
                                                    checked="checked"
                                                <?php endif ?>
                                            />
                                            <label class="label" for="cart-<?= /* @noEscape */ $_itemId ?>-term1">
                                                <span><?= $escaper->escapeHtml(__('Until canceled')) ?></span>
                                            </label>
                                        </div>
                                        <div>
                                            <input type="radio"
                                                   id="cart-<?= /* @noEscape */ $_itemId ?>-term0"
                                                   name="cart[<?= /* @noEscape */ $_itemId ?>][term]"
                                                   value="0"
                                                <?php if (!$block->getDefaultUntilCancelled()): ?>
                                                    checked="checked"
                                                <?php endif ?>
                                            />
                                            <label class="label" for="cart-<?= /* @noEscape */ $_itemId ?>-term0">
                                                <span><?= $escaper->escapeHtml(__('Stop after')) ?></span>
                                                <input type="number"
                                                       name="cart[<?= /* @noEscape */ $_itemId ?>][period]"
                                                       id="cart-<?= /* @noEscape */ $_itemId ?>-period"
                                                       class="input-text period"
                                                       data-validate='{
                                                       "required-number":true,
                                                       "validate-number-range":"2-9999999999"
                                                       }'
                                                       value="<?= /* @noEscape */ $block->getDefaultPeriod() ?>"
                                                >
                                                <span><?= $escaper->escapeHtml(__('payment(s)')) ?></span>
                                            </label>
                                        </div>
                                    <?php endif;?>
                                </div>
                            </div>
                        </div>
                        <?php if ($block->getIsVisibleStartOn()): ?>
                            <div class="fieldset">
                                <div class="field date">
                                    <label class="label">
                                        <span><?= $escaper->escapeHtml(__('Delivery Schedule')) ?>:</span>
                                    </label>
                                    <div class="control delivery-schedule">
                                        <span><?= $escaper->escapeHtml(__('First delivery on')); ?></span>
                                        <span class="cart-<?= /* @noEscape */ $_itemId ?>-delivery-schedule-date">
                                        </span>
                                        <input type="hidden"
                                               name="cart[<?= /* @noEscape */ $_itemId ?>][start_on_alt]"
                                               id="cart-<?= /* @noEscape */ $_itemId ?>-start_on_alt"
                                        />
                                        <a href="#" class="action change-delivery-date-<?= /* @noEscape */ $_itemId ?>">
                                            <?= $escaper->escapeHtml(__('change')) ?>
                                        </a>
                                        <span class="start-on-wrapper-<?= /* @noEscape */ $_itemId ?>"
                                              style="display: none;">
                                            <input type="text"
                                                   name="cart[<?= /* @noEscape */ $_itemId ?>][start_on]"
                                                   class="start-on"
                                                   id="cart-<?= /* @noEscape */ $_itemId ?>-start_at"
                                                   value="<?= /* @noEscape */ $block->getDefaultStartOn() ?>"
                                            />
                                            <a href="#"
                                               class="action update-delivery-date-<?= /* @noEscape */ $_itemId ?>">
                                                <?= $escaper->escapeHtml(__('Update')) ?>
                                            </a>
                                        </span>
                                    </div>
                                </div>
                            </div>
                        <?php endif ?>
                    </div>
                    <?php if ($block->getIsVisibleStartOn()): ?>
                        <script type="text/javascript">
                            require([
                                "jquery",
                                "mage/calendar"
                            ], function($) {
                                var changeDeliveryDateLink = $('.action.change-delivery-date-<?= /* @noEscape */ $_itemId ?>'),
                                    updateDeliverDateButton = $('.action.update-delivery-date-<?= /* @noEscape */ $_itemId ?>'),
                                    startOnWrapper = $('.start-on-wrapper-<?= /* @noEscape */ $_itemId ?>'),
                                    startOnFormattedInput = $('#cart-<?= /* @noEscape */ $_itemId ?>-start_on_alt'),
                                    deliveryScheduleDate = $('.cart-<?= /* @noEscape */ $_itemId ?>-delivery-schedule-date');
                                $("#cart-<?= /* @noEscape */ $_itemId ?>-start_at").calendar({
                                    showsTime: false,
                                    dateFormat: "<?= /* @noEscape */ $block->getDateFormat() ?>",
                                    buttonImage: "<?= /* @noEscape */ $block->getViewFileUrl('Magento_Theme::calendar.png') ?>",
                                    buttonText: "<?= $escaper->escapeHtml(__('Select Date')) ?>",
                                    showOn: 'both',
                                    minDate: "<?= /* @noEscape */ $block->getMinStartOn() ?>",
                                    altField: "#cart-<?= /* @noEscape */ $_itemId ?>-start_on_alt",
                                    altFormat: "MM dd"
                                }).datepicker('setDate', '<?= /* @noEscape */ $block->getDefaultStartOn() ?>');
                                deliveryScheduleDate.html($('#cart-<?= /* @noEscape */ $_itemId ?>-start_on_alt').val());
                                changeDeliveryDateLink.on('click', function (e) {
                                    e.stopImmediatePropagation();
                                    e.preventDefault();
                                    startOnWrapper.show();
                                    changeDeliveryDateLink.hide();
                                });
                                updateDeliverDateButton.on('click', function (e) {
                                    e.stopImmediatePropagation();
                                    e.preventDefault();
                                    changeDeliveryDateLink.show();
                                    startOnWrapper.hide();
                                    deliveryScheduleDate.html(startOnFormattedInput.val());
                                });
                            });
                        </script>
                    <?php endif ?>
                </div>
            </div>
    <?php endif; ?>
    <?php if ($block->isOneTimeAndSubscribePurchase()): ?>
            <div class="addtocart-onetime">
                <input type="radio"
                       id="cart-<?= /* @noEscape */ $_itemId; ?>-onetime"
                       name="cart[<?= /* @noEscape */ $_itemId; ?>][subscribe_active]"
                       value="0"
                    <?php if (!$groupsViewModel->isSubscriptionItem($_item)): ?>
                        checked="checked"
                    <?php endif; ?>
                />
                <label for="cart-<?= /* @noEscape */ $_itemId; ?>-onetime">
                    <?= $escaper->escapeHtml(__('Purchase')) ?>
                </label>
            </div>
    <?php endif; ?>
        </div>
    </div>
<?php endif; ?>
