<?php /* @var \TNW\Subscriptions\Block\Subscription\Summary\Overview $block */ ?>
<div class="subscription-data-wrapper ">
    <?= $block->getTabMessagesHtml()  ?>
    <div class="overview-content">
        <?php if ($block->getCanShowNextPayment()): ?>
            <div class="summary-item next-payment"><?= $block->getNextPaymentHtml() ?></div>
        <?php endif ?>
        <div class="summary-item status-message <?= /* @noEscape */ $block->getStatusMessageBlockClass() ?>">
            <div class="bordered subscription-message <?= /* @noEscape */ $block->getBlockMessage()->getStatusClass() ?>">
                <?= $block->getMessageHtml() ?>
            </div>
            <div class="bordered subscription-status <?= /* @noEscape */ $block->getBlockStatus()->getStatusClass() ?>">
                <?= $block->getStatusHtml() ?>
            </div>
        </div>
    </div>
    <div class="clear"></div>
    <div class="summary subscription-next-payment-date"><?= $block->getNextPaymentDateFormHtml() ?></div>
    <div class="summary-item subscription-products"><?= $block->getProductsHtml() ?></div>
    <?php if ($block->canShowDangerZone()): ?>
        <div class="summary-item subscription-danger-zone"><?= $block->getDangerZoneHtml() ?></div>
    <?php endif ?>
</div>
