<?php
/* @var $block \TNW\Subscriptions\Block\Subscription\Billing\CouponInformation */
?>
<div class="block">
    <div class="block-title">
        <strong>Used Coupon</strong>
    </div>
    <div class="block-content subscription-profile-coupon">
        <?php if ($block->getCouponCode()): ?>
        <table class="table-secondary data-table">
            <tbody>
            <tr class="col-0">
                <td class="label"><?= /* @noEscape */ __('Code') ?>:</td>
                <td class="right"><span class="text"><?= /* @noEscape */ $block->getCouponCode() ?></span></td>
            </tr>
            <tr class="col-1">
                <td class="label"><?= /* @noEscape */ __('Status') ?>:</td>
                <td class="right"><span class="text"><?= /* @noEscape */ $block->isCouponValid() ? __('Valid') : __('Not valid') ?></span></td>
            </tr>
            </tbody>
        </table>
        <?php else: ?>
        <div>
            <?= /* @noEscape */ __('Coupon not used') ?>
        </div>
        <?php endif; ?>
    </div>
</div>
