<?php
/**
 * Copyright © 2018 TechNWeb, Inc. All rights reserved.
 * See TNW_LICENSE.txt for license details.
 */
?>
<?php /* @var TNW\Subscriptions\Block\Subscription\Summary\Overview\DangerZone $block */ ?>
<div class="block">
    <div class="block-title danger-zone">
        <strong class="danger-zone-title"><?= __("Danger Zone") ?></strong>
    </div>
    <div class="block-content">
        <?php if ($block->isPlaceOnHoldActive()): ?>
            <div>
                <button class="action primary place-on-hold">
                    <?= __('Place on Hold') ?>
                </button>
                <span class="place-on-hold-comment">
                    <?= __('Place subscription On Hold. While "On Hold" you will not be billed.') ?>
                </span>
            </div>
            <script>
                require([
                    'jquery',
                    'Magento_Ui/js/modal/confirm',
                    'text!TNW_Subscriptions/template/grid/pause-radio-set.html'
                ], function($, confirm, pauseRadioSetTmpl) {
                    $('.action.place-on-hold').on('click', function () {
                        confirm({
                            title: $.mage.__('Warning!'),
                            content: $.mage.__('Are you sure? While "On Hold" you will not be billed.')
                                + pauseRadioSetTmpl,
                            actions: {
                                confirm: function(){
                                    var data = {
                                        isAjax: true,
                                        suspension_type: $('[name=suspension_type]:checked').val(),
                                        cycles_count: $('[name=cycles_count]').val()
                                    }
                                    $('body').trigger('processStart');
                                    $.post('<?= $block->getPlaceOnHoldUrl() ?>', data)
                                        .always(function() {
                                            window.location.reload();
                                        });
                                }
                            }
                        })
                    })
                });
            </script>
        <?php endif ?>
        <?php if ($block->isReActiveActive()): ?>
            <div style="margin-top: 1%">
                <button onclick="window.location.href='<?= $block->getReActivateUrl() ?>'"
                        class="action primary place-on-hold">
                    <?= __('Resume') ?>
                </button>
                <span class="re-activate-comment">
                    <?= __('Resume subscription.') ?>
                </span>
            </div>
        <?php endif ?>
        <?php if ($block->isCancelActive()): ?>
            <div style="margin-top: 1%">
                <button onclick="window.location.href='<?= $block->getCancelUrl() ?>'"
                        class="action primary cancel-subscription">
                    <?= __('Cancel Subscription') ?>
                </button>
                <span class="cancel-subscription-comment">
                <?= __('Cancel the subscription. This action cannot be reversed.') ?>
                </span>
            </div>
        <?php endif ?>
    </div>
</div>
