<?php /* @var \TNW\Subscriptions\Block\Subscription\Summary\Address $block */ ?>
<div class="block">
    <div class="block-title">
        <strong><?php echo __('Products') ?></strong>
        <a href="<?php echo $block->getUrl('tnw_subscriptions/subscription/items', ['entity_id' => $block->getSubscriptionProfile()->getId()]) ?>" class="profile__edit_button"></a>
    </div>
    <div class="block-content">

    </div>
</div>