<?php /* @var \TNW\Subscriptions\Block\Subscription\Summary\Overview\NextPayment $block */ ?>
<div class="bordered block-next-payment">
    <div class="title"><?= /* @noEscape */ __('Estimated Payment') ?></div>
    <?php $date = $block->getNextPaymentDateParts(); ?>
    <div class="date day"><?= /* @noEscape */ $date ? $date['day'] : '--' ?></div>
    <div class="date month"><?= /* @noEscape */ $date ? $date['month'] : '--' ?></div>
    <div class="date year"><?= /* @noEscape */ $date ? $date['year'] : '--' ?></div>
    <div class="cost">
        <?= /* @noEscape */ $block->getCostFormatting() ?>
        <div class="delivery-cost"><?= /* @noEscape */ $block->getShippingCostFormatting() ?></div>
    </div>
</div>
