<?php
/**
 * Copyright © 2018 TechNWeb, Inc. All rights reserved.
 * See TNW_LICENSE.txt for license details.
 */

/**
 * @var \Magento\Wishlist\Block\Customer\Wishlist\Item\Column\Cart $block
 * @var \Magento\Wishlist\Model\Item $item
 * @var \Magento\Framework\Escaper $escaper
 */
$item = $block->getItem();
$product = $item->getProduct();
/** @var \Magento\Wishlist\ViewModel\AllowedQuantity $viewModel */
$viewModel = $block->getData('allowedQuantityViewModel');
$allowedQty = $viewModel->setItem($item)->getMinMaxQty();
$_subscriptionBlock = $block->getChildBlock('helper.customer.wishlist.item.cart');
?>
<?php foreach ($block->getChildNames() as $childName): ?>
    <?= /* @noEscape */ $block->getLayout()->renderElement($childName, false) ?>
<?php endforeach;?>
<div class="box-tocart">
    <fieldset class="fieldset">
    <?php if ($item->canHaveQty() && $product->isVisibleInSiteVisibility()): ?>
        <div class="field qty">
            <label class="label" for="qty[<?= $escaper->escapeHtmlAttr($item->getId()) ?>]">
                <span><?= $escaper->escapeHtml(__('Qty')) ?></span>
            </label>
            <div class="control">
                <input type="number" data-role="qty" id="qty[<?= $escaper->escapeHtmlAttr($item->getId()) ?>]"
                       class="input-text qty"
                       data-validate="{'required-number':true,'validate-greater-than-zero':true, 'validate-item-quantity':{'minAllowed':<?= /* @noEscape */ $allowedQty['minAllowed'] ?>,'maxAllowed':<?= /* @noEscape */ $allowedQty['maxAllowed'] ?>}}"
                       name="qty[<?= $escaper->escapeHtmlAttr($item->getId()) ?>]"
                       value="<?= /* @noEscape */ $block->getAddToCartQty($item) * 1 ?>"
                    <?= $product->isSaleable() ? '' : 'disabled="disabled"' ?> />
            </div>
        </div>
    <?php endif; ?>
    <?php if ($product->isSaleable()): ?>
        <div class="product-item-actions">
            <?php
            $_subscriptionBlock->prepareParamsToButtonsBlock(
                $product,
                null,
                'grid',
                '',
                $block->getItemAddToCartParams($item)
            );?>
            <?= $_subscriptionBlock->getButtonsHtml(true); ?>
        </div>
    <?php else: ?>
        <?php if ($product->getIsSalable()): ?>
            <p class="available stock" title="<?= $escaper->escapeHtmlAttr(__('Availability')) ?>">
                <span><?= $escaper->escapeHtml(__('In stock')) ?></span>
            </p>
        <?php else: ?>
            <p class="unavailable stock" title="<?= $escaper->escapeHtmlAttr(__('Availability')) ?>">
                <span><?= $escaper->escapeHtml(__('Out of stock')) ?></span>
            </p>
        <?php endif; ?>
    <?php endif; ?>
    </fieldset>
</div>
