<?php
/**
 * Copyright © 2017 TechNWeb, Inc. All rights reserved.
 * See TNW_LICENSE.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block TNW\Subscriptions\Block\Subscription\Shipment\AddressEdit */
?>
<?php /** @var \Magento\Customer\Helper\Address $customerAddressHelper */
$customerAddressHelper = $this->helper(\Magento\Customer\Helper\Address::class);?>
<fieldset class="fieldset-shipping" id="customer-data">
    <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Shipping Details') ?></span></legend>
</fieldset>
