<?php
/**
 * Copyright © 2017 TechNWeb, Inc. All rights reserved.
 * See TNW_LICENSE.txt for license details.
 */

/* @var $block \TNW\Subscriptions\Block\Subscription\Product\Edit */
?>
<div class="subscribe-container"
     data-mage-init='{"tnwSubscribeContainer":{
        "subscribeUrl": "<?php echo $block->escapeUrl($block->getSubscribeUrl()) ?>",
        "setQtyFromFrequency": <?php echo $block->getAllowEditSubscribeQty() ? 'false' : 'true' ?>,
        "canShowSubscribePriceBlock" : "true"
    }}'
>
    <input type="hidden" name="sub_product_id" value="<?php echo $block->getSubscriptionProductId()?>" />
    <div class="fieldset">
        <div class="field required">
            <label class="label"><span><?php echo __('Billing Frequency') ?>:</span></label>
            <div class="control">
                <div class="options-list nested">
                    <?php $currenctFrequency = $this->getCurrentFrequencyData()?>
                    <div class="field choice required">
                        <label class="label billing_frequency">
                            <span><?php echo $currenctFrequency['label'] ?></span>
                        </label>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="fieldset">
        <div class="field term">
            <label class="label"><span><?php echo __('Term') ?>:</span></label>
            <div class="control">
                <label class="label term">
                    <span><?php echo $block->getSubscriptionPeriodLabel() ?></span>
                </label>
            </div>
        </div>
    </div>
    <div class="fieldset">
        <div class="field">
            <label class="label" for="start_at"><span><?php echo __('Start On') ?>:</span></label>
            <div class="control">
                <label class="label starton">
                    <span><?php echo $block->getStartOn() ?></span>
                </label>
            </div>
        </div>
    </div>
    <div class="fieldset">
        <div class="field required">
            <label class="label" for="subscribe_qty"><span><?php echo __('Qty') ?>:</span></label>
            <div class="control">
                <input type="number"
                       name="subscribe_qty"
                       id="subscribe_qty"
                       maxlength="12"
                       value="<?php /* @escapeNotVerified */ echo $block->getSubProductQty() * 1 ?>"
                       title="<?php /* @escapeNotVerified */ echo __('Qty') ?>" 
                       class="input-text qty"
                       data-validate='<?php echo $block->escapeHtml(json_encode($block->getQtyValidators())) ?>'
                    <?php if (!$block->getAllowEditSubscribeQty()): ?>
                       disabled="disabled"
                    <?php endif ?>
                />
                <?php if (!$block->getAllowEditSubscribeQty()): ?>
                    <input type="hidden"
                           name="subscribe_qty"
                           id="subscribe_qty_hidden"
                           value="<?php /* @escapeNotVerified */ echo $block->getSubProductQty() * 1 ?>"
                    />
                <?php endif ?>

            </div>
        </div>
    </div>
    <button type="button"
            id="product-subscribe-button"
            title="<?php echo $block->escapeHtml(__('Subscribe')) ?>"
            class="action primary subscribe"
            >
        <span data-role="button-text"><?php /* @escapeNotVerified */ echo __('Modify Cart') ?></span>
    </button>
</div>
