<?php
/* @var \TNW\Subscriptions\Block\Subscription\Summary\Payment\EmailDetails $block */
?>
<h3><?= /* @noEscape */ __("Payment Details") ?></h3>
<p>
    <strong><?= /* @noEscape */ __('Payment Type') ?>:</strong>
    <br>
    <?= /* @noEscape */ $block->getPaymentMethodTitle() ?>
</p>
<?php if ($additionalInfo = $block->getPaymentAdditionalInfo()):?>
    <?php if (isset($additionalInfo['cc_type']) || isset($additionalInfo['cc_last_4'])): ?>
    <p>
        <strong><?= /* @noEscape */ __('Card Type') ?></strong>
        <br>
        <?= /* @noEscape */ $block->getCreditCardTypeLabel() ?>
    </p>
    <p>
        <strong><?= /* @noEscape */ __('Card Number') ?></strong>
        <br>
        <?= /* @noEscape */ $block->getCreditCardNumber() ?>
    </p>
    <p>
        <strong><?= /* @noEscape */ __('Exp. Date') ?></strong>
        <br>
        <?= /* @noEscape */ $block->getCreditCardExpDate() ?>
    </p>
    <?php endif; ?>
    <?php if (isset($additionalInfo['po_number'])): ?>
        <p>
            <strong><?= /* @noEscape */ __('Purchase Order Number') ?></strong>
            <br>
            <?= /* @noEscape */ $block->getPurchaseOrderNumber() ?>
        </p>
    <?php endif; ?>
<?php endif; ?>
<p>
    <strong><?= /* @noEscape */ __('Currency') ?></strong>
    <br>
    <?= /* @noEscape */ $block->getProfileCurrencyCode() ?>
</p>
