<?php
/**
 * Copyright © 2017 TechNWeb, Inc. All rights reserved.
 * See TNW_LICENSE.txt for license details.
 */

/* @var $block \TNW\Subscriptions\Block\Subscription\Info\Billing */
?>
<div class="subscription-data-wrapper">
    <?php echo $block->getTabMessagesHtml(); ?>
    <div class="billing-info-content content-block">Here is current subscription billing info</div>
    <div class="payment-details-content content-block"
         data-mage-init='{"tnwSubscribeBilling":{
        "showEdit": "<?php echo $block->isShowEdit() ?>"
    }}'>
        <div id="payment-details-view">
            <?php echo $block->getPaymentDetailsViewHtml() ?>
        </div>
        <div id="payment-details-edit">
            <?php echo $block->getPaymentDetailsEditHtml() ?>
        </div>
    </div>
</div>
