<?php
/**
 * Copyright © 2017 TechNWeb, Inc. All rights reserved.
 * See TNW_LICENSE.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block TNW\Subscriptions\Block\Subscription\EditForm */
?>

<form class="<?php echo $block->getFormClass()?>"
      id="<?php echo $block->getFormId()?>"
      enctype="multipart/form-data"
      data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>"
      method="post">
    <?php echo $block->getFormContentHtml() ?>
    <div class="actions-toolbar">
        <div class="grid-row">
            <div class="grid-col2-xs primary">
                <button id="save_address"  class="action save primary" title="<?php /* @escapeNotVerified */ echo __('Save Address') ?>">
                    <span><?php /* @escapeNotVerified */ echo __('Save') ?></span>
                </button>
            </div>
            <div class="grid-col2-xs secondary">
                <button id="cancel-save" class="action cancel" data-action="cancel" title="<?php /* @escapeNotVerified */ echo __('Cancel') ?>">
                    <span><?php /* @escapeNotVerified */ echo __('Cancel') ?></span>
                </button>
            </div>
        </div>
    </div>
</form>
