<?php
/**
 * Copyright © 2017 TechNWeb, Inc. All rights reserved.
 * See TNW_LICENSE.txt for license details.
 */

/* @var $block \TNW\Subscriptions\Block\Subscription\Info\Shipment */
?>
<div class="subscription-data-wrapper shipment-wrapper"
     data-mage-init='{"tnwSubscribeShipment":{
        "saveAddressUrl": "<?php echo $block->escapeUrl($block->getSaveAddressUrl()) ?>",
        "showEdit": "<?php echo $block->isShowEdit() ?>",
        "customerAddressesData": "<?php echo $block->escapeQuote($block->getCustomerAddressesData())?>"
    }}'>
    <?php echo $block->getTabMessagesHtml(); ?>
    <div class="shipping-info-content">
        <div id="shipping-info-view"><?php echo $block->getShippingInfoViewHtml() ?></div>
        <div id="shipping-info-edit"><?php echo $block->getShippingInfoEditHtml() ?></div>
    </div>
</div>
