<?php
/**
 * Copyright © 2017 TechNWeb, Inc. All rights reserved.
 * See TNW_LICENSE.txt for license details.
 */

/* @var $block \TNW\Subscriptions\Block\Product\View\Subscribe */
?>

<?php if (!$block->isSubscribeAvailable()): ?>
    <?php echo $block->getChildHtml('addtocart_orig') ?>
<?php else: ?>
    <div class="addtocart-tabs" data-mage-init='{"tabs":{"openedState":"active"}}'>
        <div class="title-container">
            <div class="tab-title" data-role="collapsible" tabindex="0">
                <a href="#subscribe-tab">
                    <?php /* @escapeNotVerified */ echo __('Subscribe') ?>
                </a>
            </div>
            <div class="tab-title" data-role="collapsible" tabindex="1">
                <a href="#addtocart-tab">
                    <?php /* @escapeNotVerified */ echo __('One Time Purchase') ?>
                </a>
            </div>
        </div>
        <div class="content-container">
            <div class="tab-content subscribe-tab" id="subscribe-tab" data-role="content">
                <?php echo $block->getChildHtml('addtocart_subscribe') ?>
            </div>
            <div class="tab-content" id="addtocart-tab" data-role="content" style="display:none">
                <?php echo $block->getChildHtml('addtocart_orig') ?>
            </div>
        </div>
    </div>
<?php endif ?>
